### PR TITLE
Fix #1497: Disallow exporting of abstract class

### LINKED ISSUE #1497: JSExport of abstract class should fail more elegantly
When I tried to export a Scala abstract class, the `fastOptJS` command fails with this error:

	[error] Referring to non-existent method Last_Statement.toIntermediate__sci_List
	[error]   called from Last_StatementHelper$.statementsToIntermediate__sci_List__sci_List
	[error]   called from Last_IfElse.toIntermediate__sci_List
	[error]   called from Last_Expr.toIntermediate__T2
	[error]   called from Last_Return.toIntermediate__sci_List
	[error]   called from Last_StatementHelper$.statementsToIntermediate__sci_List__sci_List
	[error]     (already seen, not repeating call stack)
	[error] involving instantiated classes:
	[error]   Last_StatementHelper$
	[error]   Last_IfElse
	[error]   Last_Var
	[error]   Last_FunctionCall
	[error]   Last_IfExpression
	[error]   Last_Lit
	[error]   Last_Load
	[error]   Last_PointerToName
	[error]   Last_BinOp
	[error]   Last_StringLiteral
	[error]   Last_Expr
	[error]   Last_Return

When I google that, I end up [here](https://github.com/scala-js/scala-js/issues/1394), from which I managed to guess that the problem was that abstract classes require `ClassManifest`s, which breaks the linker.

It would be great if this error message were more obvious: when you try to run the JSExport macro on a abstract class, it should fail immediately.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
Seems 2.10.x doesn't have the `isAbstract` method.

**Comment by gzm0** [comment]
Updated

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
