### PR TITLE
Fix #1932: Recognize 2.12.0-M3's new shape of spurious classOf[T] trees.

### LINKED ISSUE #1932: Community build of 2.12.x failing
See https://gitter.im/scala-js/scala-js?at=561294d5ff22c70f6fac2111

### PR DESCRIPTION
**Pull request by sjrd**
The scala/scala PR https://github.com/scala/scala/pull/4749 changed the shape of the spurious `Predef.classOf[T]` that reach the `jsinterop` phase. Previously they looked like `scala.this.Predef.classOf[T]`, where as now they are `scala.Predef.classOf[T]`.

This commit generalizes the shapes of trees we recognize, so that both patterns are matched.

### CODE REVIEW

**Comment by sjrd** [comment]
Tested locally with the staging repos of 2.12.0-M3.

Review by @lrytz.
Also @gzm0 if you're around, but given the urgent nature of the fixup, I might go ahead and merge pretty quickly if it can help @lrytz with the community build and the 2.12.0-M3 release.

**Comment by lrytz** [comment]
LGTM, thanks for the very quick fix!

**Comment by sjrd** [comment]
Thanks for the inspection of the commits and the suspect list! I wouldn't have been able to fix it quite so quickly without that.

**Comment by SethTisue** [comment]
I'll run a new community build against this PR as soon as the current one finishes.

**Comment by SethTisue** [comment]
Hmm — I guess I shouldn't run the new community build until the status here is green?

**Comment by SethTisue** [comment]
Jenkins was idle anyway so I went ahead and ran it; the scala-js portion of https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/164/console is green (with [this change](https://github.com/SethTisue/community-builds/commit/dfaf6428fcd8c3bbdf3a9bf2ac402c78dad96e20)), so this looks good from our end

**Comment by sjrd** [comment]
Good! The failure here is spurious. Jenkins, retest this please

**Pull request merged**
