### PR TITLE
Build for 2.12.0-M3

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by sjrd** [comment]
OK. I'm thinking the second commit should be squashed into the first one. WDYT?

**Comment by nicolasstucki** [comment]
I just put it apart in the RP to expose clearly the issues they address.

**Comment by sjrd** [comment]
OK, but #1893 was more a reminder than an issue. I'd just put that commit line as a paragraph in the full commit, then.

**Comment by nicolasstucki** [comment]
Ok

**Comment by nicolasstucki** [comment]
Dear Jenkins, retest this please

**Comment by sjrd** [comment]
Not all partests are classified correctly:
```
--- Classified Tests
+++ Existing Tests
@@ -630 +629,0 @@
-neg/t6666d.scala
@@ -893 +891,0 @@
-neg/warn-unused-imports.scala
@@ -1033 +1030,0 @@
-pos/list-optim-check.scala
@@ -3780 +3776,0 @@
-run/t8346.scala
```
But otherwise it passed :-) Seems the JRE upgrade solved the earlier issue.

**Comment by sjrd** [comment]
Oh, needs a rebase. Probably because of #1954 which changed the whitelist and blacklist files.

**Comment by sjrd** [comment]
LGTM

**Comment by xuwei-k** [comment]
Do you have a schedule about next version with Scala 2.12.0-M3?

**Comment by sjrd** [comment]
No, but I'll try to "patch up" 0.6.5 and back-publish it for 2.12.0-M3.

**Pull request merged**
