### PR TITLE
Fix one potential race condition in startup of PhantomComRunner.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
CI only. Even if it passes, I'll relaunch it a few times to test whether this fixes our intermittent issue with "PhantomJS isn't connected".

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
OK it seems that this is actually working :)

@benjaminjackman It would be great if you could test this branch with your project, on your CI server. To do so, you'll need to setup your project to use 0.6.0-SNAPSHOT, and the following commands to be executed at the beginning of your CI script:
```
$ git clone -b fix-phantomjs-not-connected https://github.com/sjrd/scala-js.git
$ cd scala-js
$ YOUR_PROJECT_SCALA_VERSION=2.11.5
$ sbt ++$YOUR_PROJECT_SCALA_VERSION compiler/publishLocal library/publishLocal javalibEx/publishLocal testInterface/publishLocal jasmineTestFramework/publishLocal stubs/publishLocal
$ sbt ++2.10.4 ir/publishLocal tools/publishLocal jsEnvs/publishLocal testAdapter/publishLocal sbtPlugin/publishLocal
$ cd ..
```

**Comment by benjaminjackman** [comment]
@sjrd I will try them out

**Comment by gzm0** [comment]
@sjrd you are the man!!! Nice!. Small nit: I suppose you checked that Jetty does not have a method `isRunning` we could store instead of duplicating state, right :)

**Comment by sjrd** [comment]
It does have some methods: http://archive.eclipse.org/jetty/8.0.0.M1/apidocs/org/eclipse/jetty/util/component/LifeCycle.html#isRunning%28%29
Apparently I should reuse `isStarted()`? And probably rename the method `WebsocketListener.onRunning` to `onStarted`?

**Comment by sjrd** [comment]
But I fear that the server's `isStarted` method will return `false` when it stops, which would then deadlock our thing.

**Comment by gzm0** [comment]
Ok. Let's leave it that way

**Comment by benjaminjackman** [comment]
@sjrd Ok so I had to upgrade our jenkins server anyhow because it was very slow, so I spent the morning doing that. Since the upgrade I have not been able to replicate the error. This leads me to believe that issue was clearly related to some sort of race. So looking at this commit it seems likely that it could fix the issue, but I can't verify it. I am very sorry. I might be able to try running it on a slow machine and see if I can replicate it again and if so use the snapshot and then see if it fixes the issue. I feel really bad that I can't give a better verification especially given how quickly you worked to fix the issue.

**Comment by sjrd** [comment]
OK no worries. This fix is useful on its own anyway, apparently, since it seems to fix our intermittent issue with the same error message.
I'll rerun the test 4 or 5 more times just to be sure before merging this.

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
Nooooooo! Two cases of Phantom.js not connected:
https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/26725/console
https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/26734/console

I'll revert the changes to `ci/matrix.xml`. But the changes still deserve to get it. There *was* a potential issue. It's just not the last one :-(

**Pull request merged**
