### PR TITLE
Fix #4281: Do not treat anonymous JS classes as lambdas

### LINKED ISSUE #4281: Bad error message when trying to define `apply` in an anonymous class extending js.Function
While trying to break our detection of JS functions, I found this:

```scala
@js.native
@JSGlobal("bad")
abstract class BadFunction extends js.Function1[Int, String]

object Test {
  new BadFunction {
    def apply(x: Int): String = "f"
  }
}
```

This fails to compile with the following error:

```
Concrete members of JS native types may only call js.native.
      def apply(x: Int): String = "f"
                                  ^
```

Note that this does *not* happen for other native traits:

```scala
@js.native
trait MyTrait[T] extends js.Object {
  def apply(): T
}

@js.native
@JSGlobal("bad")
abstract class BadMyTrait extends MyTrait[Int]

object Test {
  new BadMyTrait {
    def apply(): Int = 1
  }
}
```

This fails as expected with:

```
A non-native JS class cannot declare a method named `apply` without `@JSName`
      def apply(): Int = 1
          ^
```

### PR DESCRIPTION
**Pull request by gzm0**
This merely improves the error messages.

### CODE REVIEW

**Comment by gzm0** [comment]
I know we have agreed to disallow inheriting from `js.FunctionN` for non-native classes. It started bothering me that we treat `js.FunctionN` special in that regard. IMO a nicer approach is to fix #4282. It is then impossible by construction to inherit non-natively, concretely from `js.FunctionN`.

**Review by sjrd — APPROVED** [review]
IIUC this can go in 1.3.1, because it only changes the error message?

**Comment by gzm0** [comment]
Yep, this can go into 1.3.1.

**Comment by sjrd** [comment]
👍 

It doesn't seem to work in 2.11, though :(

**Comment by gzm0** [comment]
It got more hacky but it works :S WDYT?

**Review by sjrd — APPROVED** [review]
Looks good to me. It's not even that hacky. ;)

**Pull request merged**
