### PR TITLE
Fix #1532: Fix TypedArrayDoubleBuffer.bytesPerElem.

### LINKED ISSUE #1532: TypedArrayByteBuffer.asDoubleBuffer results in a "RangeError: Invalid typed array length"
I suspect a minor typo on [this line](https://github.com/scala-js/scala-js/blob/184217741a2291c72833dcf7299a5daad6fadb94/javalib/src/main/scala/java/nio/TypedArrayDoubleBuffer.scala#L99): ```def bytesPerElem = 2```

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by gzm0** [comment]
Hahahahaha, so many tests for one line of code :P

**Comment by sjrd** [comment]
Yep ^^ But that's because they also test things for all the other data types. Turns out all the `asXBuffer` that should result in `TypedArrayBuffer`s were never tested ^^

**Comment by sjrd** [comment]
And it's not even just one *line*, it's one *character* ^^
(reminds me of #1454)

**Pull request merged**
