### PR TITLE
Fix #2842: Remove the jsdom environment from the core.

### LINKED ISSUE #2842: Move JSDOMNodeJSEnv out of the core
With `jsDependencies` gone from the core #2841, there will be no further dependency on `JSDOMNodeJSEnv` in the rest of the sbt plugin. Therefore, `JSDOMNodeJSEnv` can itself be moved outside of the core, just like all the other JS envs (except the basic Node.js one).

### PR DESCRIPTION
**Pull request by sjrd**
Node.js with jsdom support moved to the separate repository https://github.com/scala-js/scala-js-env-jsdom-nodejs.

After these changes, `git grep -i jsdom` turns up empty.

### CODE REVIEW

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js-env-jsdom-nodejs/pull/1 must be merged before this gets in.

**Comment by gzm0** [comment]
By the way I'm not 100% convinced that the public interface we expose for `JSEnv` implementations (i.e. `AbstractNodeJSEnv` and `ExternalJSEnv`) is optimal. I'd like to rethink it before 1.0.0 (maybe more composition and less inheritance ;)).

**Comment by gzm0** [comment]
But I'm OK to go forward with this to unblock 1.0.0-M1.

**Comment by sjrd** [comment]
I'd also like to rethink the `JSEnv` public interface. It's definitely not optimal.

**Pull request merged**
