### PR TITLE
Pass `remoteArgs` to `Slave` in test interface

### PR DESCRIPTION
**Pull request by Duhemm**
I guess this was a typo.

### CODE REVIEW

**Comment by sjrd** [comment]
Dear Jenkins, test this please

**Comment by sjrd** [comment]
I'll have a look sometime during the week. Probably a typo indeed, but I'd like to understand this `remoteArgs` in the process.

**Comment by gzm0** [comment]
> Probably a typo indeed, but I'd like to understand this `remoteArgs` in the process.

I'd like to understand `remoteArgs` as well :P Feel free to investigate more. From my side, this LG.

**Comment by gzm0** [comment]
Also: This should probably target 0.6.x?

**Comment by sjrd** [comment]
Ah yes, it should definitely target 0.6.x. @Duhemm could you rebase on top of the `0.6.x` branch and change the target branch of this PR please?

**Comment by Duhemm** [comment]
@sjrd Done.

**Comment by sjrd** [comment]
Thanks. Jenkins, retest this please

**Comment by sjrd** [comment]
The best lead I found was in ScalaTest's codebase: https://github.com/scalatest/scalatest/blob/d52e2a2b7c49f988c8ed3a5728faec7c641be03e/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L904
Which suggests that this is used when testing is done in a forked JVM. Another interesting place to look at is https://github.com/scalatest/scalatest/blob/d52e2a2b7c49f988c8ed3a5728faec7c641be03e/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L770

All of that is probably irrelevant in Scala.js, since we don't support the fork mode (or rather, we only have a fork mode but with our own serialization mechanisms under the hood).

**Pull request merged**
