### PR TITLE
Fix #1991: Make the strong mode output pass on Node.js 4.

### LINKED ISSUE #1991: The Strong Mode output is broken on Node.js 4
Probably because we're not actually compliant, and the new version contains more checks.

### PR DESCRIPTION
**Pull request by sjrd**
This PR fixes a number of smallish issues that made our strong mode output invalid on Node.js 4. It leaves one major thing unsolved: the encoding of Scala.js-defined JS classes, which is filed as a separate issue #2137. In the meantime, we deactivate those tests in strong mode.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki and @gzm0

**Comment by sjrd** [comment]
retest this please

**Comment by gzm0** [comment]
That's all. Just minor things. LGTM otherwise.

**Comment by sjrd** [comment]
Updated.

**Comment by gzm0** [comment]
LGTM

**Comment by nicolasstucki** [comment]
That's all. Otherwise LGTM.

**Comment by sjrd** [comment]
Updated.

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
