### PR TITLE
Enable UndefOr operators for `Unit | _` and `_ | Unit`

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by sjrd** [comment]
Could you motivate this please?

**Comment by Atry** [comment]
1. `UndefOr` and `Unit | ?` are essentially the same type
2. Some tools produce `Unit | _` types when converting type definition from TypeScript

**Comment by sjrd** [comment]
So, in fact in Scala.js 1.x `js.UndefOr[A]` *is* literally a type alias for `A | Unit`. I guess we could pimp the `UndefOrOps[A]` to `A | Unit` in 0.6.x to bridge the gap a bit.

That said, tools right now really should emit `js.UndefOr[A]` instead of `A | Unit`/`Unit | A`. I feel like this PR is trying to work around the tools inside the core, whereas in fact we should just fix the tools, not change the core.

**Comment by Atry** [comment]
Is there a plan for releasing Scala.js 1.0?

**Comment by sjrd** [comment]
Not really. We "just" need to clear out https://github.com/scala-js/scala-js/milestone/64

**Comment by Atry** [comment]
Will the milestone break backward compatibility?

**Comment by sjrd** [comment]
It's unlikely that we will break anything at the source level for user-visible stuff, at this point. So the release notes of M7 will be very similar to those of M6, and likewise for future milestones until the final release.

**Comment by Atry** [comment]
Since backward-compatibility will be kept from 1.0.0-M6, why not release now and let new features and internal refactoring go to Scala.js 1.1+?

**Comment by sjrd** [comment]
Because the internal refactorings affect the *binary* compatibility of the artifacts.

**Comment by Atry** [comment]
It is to say it's only necessary to clear out IR related issues, isn't it? Is it possible to breaking change internal compiler API after 1.0?

> Because the internal refactorings affect the _binary_ compatibility of the artifacts.

**Comment by sjrd** [comment]
The *compiler* API we break all the time (in fact we don't even consider it an API at all). But the surface of the linker API, as well as the `JSEnv` API, will also need to preserve binary compatibility after 1.x.

**Comment by gzm0** [comment]
What is the state of this? @Atry would you still like us to consider this for merging or are you OK with using 1.0.x / improving tools?

**Comment by Atry** [comment]
I understand that the Scala.js maintainers are not willing to accept changes that do not help in future Scala 1.0.

**Comment by sjrd** [comment]
I've thought more about this, and in particular how this is going to evolve in Scala 3. Since it will have real union types, `String | Null` will be equivalent to `String`, and therefore the proposed API will not be able to kick in. Unless Scala 3 receives non-nullable types as well, that means the change introduced here will be broken by Scala 3. For that reason I'm going to close this. It could be revisited if Scala 3 gets non-nullable types.

**Pull request closed without merging**
