### PR TITLE
Catch up with 2.12.0-RC1

### PR DESCRIPTION
**Pull request by adriaanm**
Compensating PR for scala/scala#5331 and scala/scala#5294. The community build passes for me with these changes (Community build issue tracked as scala/scala-dev#203).

### CODE REVIEW

**Comment by sjrd** [comment]
Looks good. Could you just capitalize the commit message of the first commit? ("Add ..."). Maybe even say `Add missing 'override' ...` since it was indeed missing, even if the compiler did not report it.

We have technical difficulties with our CI this week and @fsalvi is on vacation, so testing and merging this PR might be delayed a few days.

**Comment by adriaanm** [comment]
Done! FYI, we're hoping to stage RC1 next week.

**Comment by sjrd** [comment]
>FYI, we're planning to stage RC1 next week.

Hum, good to know. I guess either we'll have to publish a very small 0.6.12 release with this patch and the 2 other fixes we have so far; or we'll hotfix 0.6.11 with just this PR to be able to publish 0.6.11 for 2.12.0-RC1.

**Comment by sjrd** [comment]
LGTM Jenkins, test this please

**Pull request merged**
