### PR TITLE
Fix #1816: Update 2.12.0-M1 with 2.12.0-M2

### LINKED ISSUE #1816: Build for 2.12.0-M2
To add in our build/CI/publish scripts for the next version.

### PR DESCRIPTION
**Pull request by nicolasstucki**
* Update all 2.12.0-M1 version tags to 2.12.0-M2
* Add partests for 2.12.0-M2
* Override for ScalaRuntime in 2.12

### CODE REVIEW

**Comment by sjrd** [comment]
This needs a rebase on top of master. It doesn't merge.

**Comment by sjrd** [comment]
Partest for 2.12.0-M2 should be added to the CI matrix. I recommend to do this in nightly. So at the end of the `<matrix id="nightly">` you'll find that:
```xml
    <run task="partest-noopt">
      <v n="scala">2.11.7</v>
      <v n="java">1.7</v>
    </run>
    <run task="partest-fastopt">
      <v n="scala">2.11.7</v>
      <v n="java">1.7</v>
    </run>
    <run task="partest-fullopt">
      <v n="scala">2.11.7</v>
      <v n="java">1.7</v>
    </run>
```
copy and paste those, and change the Scala and Java versions of the copy to 2.12.0-M2 and 1.8, respectively.

**Comment by sjrd** [comment]
The first commit title should says 2.12.0-M2 rather than just 2.12.0.

**Comment by sjrd** [comment]
That's all I think.

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
Nightly is here: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/2610/

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
In the nightly partests all `run/*` for 2.12.0-M2 are failing.

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
retest this please

**Comment by sjrd** [comment]
Hum, are you sure the failures are spurious? What about the failing run tests. They should be addressed. (I haven't looked at them.)

**Comment by nicolasstucki** [comment]
There where several spurious, although there is one that does not look like it: 
```
java.lang.RuntimeException: bad constant pool tag 15 at byte 4704
	at com.typesafe.tools.mima.core.ClassfileParser$ConstantPool.errorBadTag(ClassfileParser.scala:201)
	at com.typesafe.tools.mima.core.ClassfileParser$ConstantPool.<init>(ClassfileParser.scala:103)
	at com.typesafe.tools.mima.core.ClassfileParser.parseAll(ClassfileParser.scala:67)
	at com.typesafe.tools.mima.core.ClassfileParser.parse(ClassfileParser.scala:59)
	at com.typesafe.tools.mima.core.ClassInfo.ensureLoaded(ClassInfo.scala:72)
	at com.typesafe.tools.mima.core.WithAccessModifier$class.isPublic(WithAccessModifier.scala:6)
	at com.typesafe.tools.mima.core.ClassInfo.isPublic(ClassInfo.scala:36)
	at com.typesafe.tools.mima.core.PackageInfo.com$typesafe$tools$mima$core$PackageInfo$$isAccessible$1(PackageInfo.scala:79)
	at com.typesafe.tools.mima.core.PackageInfo$$anonfun$1.apply(PackageInfo.scala:69)
	at com.typesafe.tools.mima.core.PackageInfo$$anonfun$1.apply(PackageInfo.scala:69)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:390)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:22)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:267)
	at scala.collection.AbstractIterator.toSet(Iterator.scala:1157)
	at com.typesafe.tools.mima.core.PackageInfo.accessibleClassesUnder$1(PackageInfo.scala:69)
	at com.typesafe.tools.mima.core.PackageInfo.accessibleClasses$lzycompute(PackageInfo.scala:82)
	at com.typesafe.tools.mima.core.PackageInfo.accessibleClasses(PackageInfo.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib.comparePackages(MiMaLib.scala:47)
	at com.typesafe.tools.mima.lib.MiMaLib.com$typesafe$tools$mima$lib$MiMaLib$$traversePackages(MiMaLib.scala:64)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:71)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:66)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply$mcV$sp(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.core.util.IndentedOutput$.indented(IndentedOutput.scala:11)
	at com.typesafe.tools.mima.lib.MiMaLib.com$typesafe$tools$mima$lib$MiMaLib$$traversePackages(MiMaLib.scala:65)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:71)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:66)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply$mcV$sp(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.core.util.IndentedOutput$.indented(IndentedOutput.scala:11)
	at com.typesafe.tools.mima.lib.MiMaLib.com$typesafe$tools$mima$lib$MiMaLib$$traversePackages(MiMaLib.scala:65)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:71)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1$$anonfun$apply$mcV$sp$1.apply(MiMaLib.scala:66)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply$mcV$sp(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.lib.MiMaLib$$anonfun$com$typesafe$tools$mima$lib$MiMaLib$$traversePackages$1.apply(MiMaLib.scala:66)
	at com.typesafe.tools.mima.core.util.IndentedOutput$.indented(IndentedOutput.scala:11)
	at com.typesafe.tools.mima.lib.MiMaLib.com$typesafe$tools$mima$lib$MiMaLib$$traversePackages(MiMaLib.scala:65)
	at com.typesafe.tools.mima.lib.MiMaLib.collectProblems(MiMaLib.scala:84)
	at com.typesafe.tools.mima.plugin.SbtMima$.runMima(SbtMima.scala:32)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$2.apply(MimaPlugin.scala:17)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$2.apply(MimaPlugin.scala:14)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
	at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nicolasstucki** [comment]
Actually it was failing during the resolution of some dependencies, it might not be spurious after all. It looks like a corrupt file.

**Comment by nicolasstucki** [comment]
Dear Mr. Jenkins, retest this please

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by nicolasstucki** [comment]
Those `bad constant pool tag 15` seam to caused by some miss match on the JDK versions.

**Comment by nicolasstucki** [comment]
@sjrd or @gzm0, have you encountered some similar issue in the past?

**Comment by sjrd** [comment]
Hum no, never :-s

**Comment by sjrd** [comment]
This new version fails with
```scala
java.lang.NoSuchMethodError: sbt.ModuleInfo$.apply$default$9()Lscala/collection/Seq;
	at com.typesafe.tools.mima.plugin.SbtMima$.getPreviousArtifact(SbtMima.scala:72)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaDefaultSettings$4$$anonfun$apply$3.apply(MimaPlugin.scala:41)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaDefaultSettings$4$$anonfun$apply$3.apply(MimaPlugin.scala:40)
	at scala.Option.map(Option.scala:145)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaDefaultSettings$4.apply(MimaPlugin.scala:40)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaDefaultSettings$4.apply(MimaPlugin.scala:32)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (ir/*:mimaPreviousClassfiles) java.lang.NoSuchMethodError: sbt.ModuleInfo$.apply$default$9()Lscala/collection/Seq;
```

It seems the new version of MiMa requires sbt 0.13.7 or later. It requires this commit:
https://github.com/sbt/sbt/commit/183c2bcfe2a84295deea82eed2179a72c50289cc
(at the binary compatibility level).

So we also need to update our sbt to 0.13.7 (in [`projects/build.properties`](https://github.com/scala-js/scala-js/blob/master/project/build.properties)). The funny thing is that we already use 0.13.7 in [`sbt-plugin-test/project/build.properties`](https://github.com/scala-js/scala-js/blob/master/sbt-plugin-test/project/build.properties) ^^

**Comment by sjrd** [comment]
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/2699/

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
Hum, I'm pretty sure the failures are not spurious. I get stuff like
```
[info] Loading project definition from /localhome/jenkins/a/workspace/scalajs-task-worker_2/project/project
[info] Loading project definition from /localhome/jenkins/a/workspace/scalajs-task-worker_2/project
[info] Set current project to Scala.js (in build file:/localhome/jenkins/a/workspace/scalajs-task-worker_2/)
[info] Setting version to 2.12.0-M2
[info] Reapplying settings...
[info] Set current project to Scala.js (in build file:/localhome/jenkins/a/workspace/scalajs-task-worker_2/)
[info] Resolving org.scala-js#scalajs-library;0.6.4 ...
[info] Resolving org.scala-js#scalajs-library;0.6.4 ...
[warn] 	module not found: org.scala-js#scalajs-library;0.6.4
[warn] ==== local: tried
[warn]   /localhome/jenkins/scala-js-sbt-homes/sbt-home/local/org.scala-js/scalajs-library/0.6.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-js/scalajs-library/0.6.4/scalajs-library-0.6.4.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-js#scalajs-library;0.6.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.scala-lang#scala-library;2.12.0-M2 ...
[info] Resolving org.scala-js#scalajs-compiler_2.12.0-M2;0.6.5-SNAPSHOT ...
[info] Resolving org.scala-lang#scala-compiler;2.12.0-M2 ...
[info] Resolving org.scala-lang#scala-reflect;2.12.0-M2 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12.0-M2;1.0.4 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.12.0-M2;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Resolving org.eclipse.jetty#jetty-websocket;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-util;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-io;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-http;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty#jetty-server;8.1.16.v20140903 ...
[info] Resolving org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 ...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
sbt.ResolveException: unresolved dependency: org.scala-js#scalajs-library;0.6.4: not found
```
which is a genuine unresolved dependency. It should be looking for `scalajs-library_2.12.0-M2;0.6.4` instead (and `scalajs-library_2.11;0.6.4`).

Maybe try with `Some(CrossVersion(scalaV, scalaBinaryV)(prevProjectID).cross(CrossVersion.disabled))` instead. That we do resolve ourselves like we used to, then we explicitly disable cross-versioning so that MiMa does not try to do it itself.

**Comment by sjrd** [comment]
The third commit is broken: it reverts some of the changes of the first commit ^^

**Comment by sjrd** [comment]
https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/55950/console
The partest `run/t9387b.scala` is missing in the classification.

Also, it seems the checksizes for 2.12.0-M2 are too high (same log). They should be tightened.

**Comment by sjrd** [comment]
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/2731/

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
Nightly has only one timed out configuration (which is not a partest). I'm also rebuilding it.

It seems like we're going to be good, this time :-)

**Comment by sjrd** [comment]
LGTM, btw.

**Comment by sjrd** [comment]
Yeah :)

**Pull request merged**
