### PR TITLE
Fix #1712: Add missing boxing of elements in ConcurrentSkipListSet.

### LINKED ISSUE #1712: Missing boxing of element in Java util ConcurrentSkipListSet.removeAll
`inner.remove(iter.next)` should be `inner.remove(Box(iter.next))`

### PR DESCRIPTION
**Pull request by nicolasstucki**
The bug is quite evident. I've not included test yet but I have them implemented as part of the tests that are in my java-collections-implementation brach which is almost ready for a PR.

Review by @sjrd and @andreaTP

### CODE REVIEW

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
For some reason, this does not compile on 2.10, says CI.

**Comment by nicolasstucki** [comment]
Fixed, the problem involved a type miss match and an implicit definition of `remove` that was not doing then  same in 2.11 and 2.10.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
