### PR TITLE
Fix #3571: Always load reflective call return types

### LINKED ISSUE #3571: Reflective call target determination depends on whether result types are loaded
From: #3558

> So, I had a closer look at this and it seems that this (and the previous code) simply _ignores_ if the result type of a potential reflective call target is not loaded. I suspect this could lead to non-deterministic behavior; I will try force load class infos properly here.

### PR DESCRIPTION
**Pull request by gzm0**
I have manually verified that the test fails without the fixes.

### CODE REVIEW

**Comment by gzm0** [comment]
It seems like this surfaces a bad interaction between default methods and reflective proxies:

```
Caused by: java.lang.AssertionError: assertion failed: Trying to dynamically reach the non-class method ju_Comparator.reversed__ju_Comparator
```

The method that causes the assertion is selected by `findProxyMatch` with the new code.

@sjrd any idea about this?

**Comment by gzm0** [comment]
> The method that causes the assertion is selected by findProxyMatch with the new code.

Seems this was a bug in the new code where it attempted to reach the reflective target and not the generated proxy.

**Comment by gzm0** [comment]
@sjrd I need some help here: The CI shows that the new code erroneously tries to load primitives types. So I'm unsure what to do when I encounter a name of a primitive type; It seems like I'd need something like `isSubtype` in `ir.Types` but for `TypeRef`s?

Note that whatever fix we'll find here will probably have to be backported to 0.6.

**Comment by sjrd** [comment]
Hum, it's true that the code does not seem to handle primitive types. That's weird. In any case, if it encounters any primitive type, then `isMoreSpecific` should always answer `false`. At the IR/JVM level, primitive types are always unrelated to each other. (so `short` is not more specific than `int`, for example)

**Comment by gzm0** [comment]
Even w.r.t. `Object`? Wouldn't e.g. `Int` be more specific than `Object` especially in view of generics and bridges?

**Comment by sjrd** [comment]
Yes, even with `Object`:
```scala
scala> class A { def foo(): Any = "foo"; def foo[X](): Int = 2 }
defined class A

scala> classOf[A].getMethod("foo")
res3: java.lang.reflect.Method = public java.lang.Object A.foo()
```
And also with `java.lang.Integer`:
```scala
scala> class A { def foo(): Integer = 1; def foo[X](): Int = 2 }
defined class A

scala> classOf[A].getMethod("foo")
res4: java.lang.reflect.Method = public java.lang.Integer A.foo()
```

**Comment by gzm0** [comment]
This is ready for final review.

**Pull request merged**
