### PR TITLE
Fix #2368: Support single-arg setTimeout in Rhino

### LINKED ISSUE #2368: RhinoJSEnv does not support setTimeout without second argument
This will crash:

```javascript
setTimeout(myFunction);
```

But [is valid](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout).

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$setupSetTimeout$1.apply(RhinoJSEnv.scala:290)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$setupSetTimeout$1.apply(RhinoJSEnv.scala:286)
```

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by gzm0** [comment]
Needs rebase on towards 0.6.10 commit.

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
This can now be rebased on top of master.

**Comment by gzm0** [comment]
Rebased

**Comment by sjrd** [comment]
Needs a binary compat exception:
```
[error]  * method timeoutSingleArgTest()Unit in trait org.scalajs.jsenv.test.TimeoutTests does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("org.scalajs.jsenv.test.TimeoutTests.timeoutSingleArgTest")
```
Note that, as a binary issue, it is definitely legit; it's a breaking change. But it's a source-compatible change, and that's what really matters for the test kit.

**Comment by gzm0** [comment]
Updated and rebased

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
