### PR TITLE
Fix #2461: Fix tests tait javalib.io.CommonStreamsTests.

### LINKED ISSUE #2461: Tests in javalib.io.CommonStreamsTests are not being executed.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
LGTM

**Comment by gzm0** [comment]
Can you please somewhere describe what the problem was and how you fix it?

**Comment by nicolasstucki** [comment]
I'll add documentation in the issue.

**Pull request merged**
