### PR TITLE
Fix #1805: Anchor scalastyle regex for class/object names

### LINKED ISSUE #1805: Fix class/object name regexes in scalastyle
The regexes for object/class names in our scalastyle config are not anchored. They need to be put between `^$`.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by gzm0** [comment]
I preferred the couple of ignores over allowing "_" and leading lower case in object names. WDYT?

**Comment by sjrd** [comment]
LGTM, agreed.

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
