### PR TITLE
Fix #1840: Give a meaningful `name` property to emitted classes.

### LINKED ISSUE #1840: @ScalaJSDefined  classes constructor name is empty
```scala

@ScalaJSDefined
class Hello extends ReactComponent[Any,Any] {
  val displayName = "Hello"
}

val dummyHello = new Hello()
val ctor = dummyHello.asInstanceOf[js.Dynamic].constructor
js.Dynamic.global.Hello = ctor

```
In browser console

```js
 Hello.name = ""
```

In js world 

ES6 class : 
```js
class Hello  {
}
```
Transpiled code (https://babeljs.io/repl/) 

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Hello = function Hello() {
  _classCallCheck(this, Hello);
};
```

In browser console 

```js
var x = new Hello()
x.constructor.name = "Hello"
```

I also created an issue in react : https://github.com/facebook/react/issues/4574

### PR DESCRIPTION
**Pull request by sjrd**
Instead of emitting
  `var $c_pack_Foo = function() { ... };`
we now emit
  `function $c_pack_Foo() { ... }`

Not only is this shorter, but most importantly it gives a meaningful `name` property to the function. Some debugging facilities, including those built in some frameworks, leverage this property.

Obviously, the name is only meaningful in fastOpt mode. In fullOpt, the names are shortened anyway.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki BUT DO NOT MERGE YET. I need to update checksizes, since the new encoding takes less characters in fastOpt mode. I'll let CI tell me what are the appropriate values.

**Comment by sjrd** [comment]
Updated checksizes.

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
