### PR TITLE
Fix #1685: Publish the jar of the CLI project.

### LINKED ISSUE #1685: Publish CLI JAR
Publish the JAR for the "cli" project to Maven for use by other tooling. Ref: https://groups.google.com/forum/?fromgroups&pli=1#!topic/scala-js/tcWk7IEosGk

### PR DESCRIPTION
**Pull request by sjrd**
This provides a tool- and language-agnostic entry point to the tools, which can be used by simple tasks for build tools other than sbt. Publishing the CLI allows these tools to fetch the appropriate jar through normal Maven dependencies.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0

**Comment by sjrd** [comment]
Hum let's assign this to @nicolasstucki instead.

**Comment by gzm0** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
