### PR TITLE
Fix #4878: Avoid overflow while checking bounds in regionMatches.

### LINKED ISSUE #4878: String regionMatches Runtime Error
Scala version: 2.12.18, 2.13.11, 3.3.0
Scala-js version: 1.13.1

Steps to reproduce: 

The following code snippet will produce a runtime error: 

```
val regStr = "."
val i1 = 2147483647
val str = "큥狤ꨊ꧊켋嘍ꋼꞦ桄뵝俒鴮鰌哓ཱི喑䛗⽢쁔餱ꋎ଎䀰咴Ჰ⬆䄰掯⾾₀벎﷋촦늾ᆄ"
val i2 = 2147483647
val len = 1

regStr.regionMatches(true, i1, str, i2, len)
```

On Scala-js it throws runtime error like this: 

```
[info]   should offer regionMatches methods that are consistent with String *** FAILED *** (0 milliseconds)
[info]   org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[info]   at $charAt(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:430:11)
[info]   at java.lang.String.regionMatches(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:101054:11)
[info]   at {anonymous}()(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:202467:255)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:79740:43)
[info]   at org.scalatest.OutcomeOf.outcomeOf(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:23065:11)
[info]   at org.scalatest.Transformer.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:103789:10)
[info]   at org.scalatest.funspec.AnyFunSpecLike$$anon$1.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:84438:164)
[info]   at org.scalatest.funspec.AnyFunSpecLike.invokeWithFixture$1(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127417:15)
[info]   at org.scalatest.funspec.AnyFunSpecLike.runTest(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127203:8)
[info]   at {anonymous}()(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127320:12)
[info]   Cause: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[info]   at $charAt(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:430:113)
[info]   at java.lang.String.regionMatches(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:101054:11)
[info]   at {anonymous}()(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:202467:255)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:79740:43)
[info]   at org.scalatest.OutcomeOf.outcomeOf(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:23065:11)
[info]   at org.scalatest.Transformer.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:103789:10)
[info]   at org.scalatest.funspec.AnyFunSpecLike$$anon$1.apply(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:84438:164)
[info]   at org.scalatest.funspec.AnyFunSpecLike.invokeWithFixture$1(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127417:15)
[info]   at org.scalatest.funspec.AnyFunSpecLike.runTest(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127203:8)
[info]   at {anonymous}()(/home/cheeseng/git/scalatest/js/scalactic-test/target/scala-2.12/scalactictestjs-test-fastopt/main.js:127320:12)

```

but on JVM it just returns `false`: 

```
(base) cheeseng@cheeseng-RAVEN:~$ /opt/scala/scala-2.13.11/bin/scala
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 11.0.19).
Type in expressions for evaluation. Or try :help.

scala> val regStr = "."
     | val i1 = 2147483647
     | val str = "큥狤ꨊ꧊켋嘍ꋼꞦ桄뵝俒鴮鰌哓喑䛗⽢쁔餱ꋎ଎䀰咴Ჰ⬆䄰掯⾾₀벎﷋촦 늾"
     | val i2 = 2147483647
     | val len = 1
     | 
     | regStr.regionMatches(true, i1, str, i2, len)
val regStr: String = .
val i1: Int = 2147483647
val str: String = 큥狤ꨊ꧊켋嘍ꋼꞦ桄뵝俒鴮鰌哓ཱི喑䛗⽢쁔餱ꋎ଎䀰咴Ჰ⬆䄰掯⾾₀벎﷋촦늾ᆄ
val i2: Int = 2147483647
val len: Int = 1
val res0: Boolean = false
```

Expected Behavior: 
JVM and JS should have the consistent behavior.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Review by gzm0 — APPROVED** [review]
Just one optional suggestion.

**Comment by gzm0** [comment]
Also: The issue number is wrong. It should be #4878

**Review by gzm0 — CHANGES_REQUESTED** [review]
Please fix the issue number :)

**Comment by sjrd** [comment]
Issue number fixed and additional tests added.

**Review by gzm0 — APPROVED** [review]

**Pull request merged**
