### PR TITLE
Update new collection impls to the upstream IterableCC refactoring.

### PR DESCRIPTION
**Pull request by sjrd**
See https://github.com/scala/scala/pull/7929.

Locally tested with
```
> set resolvers in Global += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
> ++2.13.0-pre-041fc23
> testSuite/test
```

### CODE REVIEW

**Comment by adriaanm** [comment]
the upstream PR is now merged

**Comment by sjrd** [comment]
@adriaanm I get the following error with the current tip of this PR:
```
> set resolvers in Global += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
> ++2.13.0-pre-041fc23
> testSuite/test
[info] Compiling 123 Scala sources to /localhome/doeraene/projects/scalajs-0.6.x/library/target/scala-2.13.0-pre-041fc23/classes...
[error] /localhome/doeraene/projects/scalajs-0.6.x/library/src/main/scala-new-collections/scala/scalajs/js/WrappedArray.scala:24: error: incompatible type in overriding
[error] protected def fromSpecific(coll: scala.collection.IterableOnce[A]): scala.scalajs.js.WrappedArray[A] (defined in trait IterableOps)
[error]   with protected def fromSpecific(coll: scala.collection.IterableOnce[A]): scala.collection.mutable.IndexedBuffer[A] (defined in trait IterableFactoryDefaults);
[error]  found   : (coll: scala.collection.IterableOnce[A])scala.collection.mutable.IndexedBuffer[A]
[error]  required: (coll: scala.collection.IterableOnce[A])scala.scalajs.js.WrappedArray[A];
[error]  other members with override errors are: newSpecificBuilder, empty
[error] final class WrappedArray[A](val array: js.Array[A])
[error]             ^
[info] one error found
[trace] Stack trace suppressed: run last library/compile:compile for the full output.
[error] (library/compile:compile) java.lang.Exception: Nonzero exit code returned from runner: 1
[error] Total time: 7 s, completed Apr 2, 2019 10:35:11 PM
```
I don't know what to do about it. I've tried:

* Explicitly overriding `fromSepcific` in `js.WrappedArray`
* Insert a `with IterableFactoryDefaults[A, WrappedArray]` at the end of the trait list of `js.WrappedArray`
* Do both at the same time

but none of these attempts changes the above error. I'm a bit lost. Any suggestion?

**Comment by adriaanm** [comment]
This compiles for me:
```
import scala.collection._


class WrappedArray[A](val array: Array[A])
  extends mutable.AbstractBuffer[A]
    with StrictOptimizedSeqOps[A, WrappedArray, WrappedArray[A]]
    with mutable.IndexedSeq[A]
    with mutable.IndexedSeqOps[A, WrappedArray, WrappedArray[A]]
    with mutable.IndexedBuffer[A]
    with mutable.Builder[A, WrappedArray[A]]
    with IterableFactoryDefaults[A, WrappedArray]
    with Serializable {
  override def iterableFactory: SeqFactory[WrappedArray] = ???
  override def knownSize: Int = super[IndexedSeqOps].knownSize

  // Members declared in scala.collection.mutable.Buffer
  def insert(idx: Int, elem: A): Unit = ???
  def insertAll(idx: Int, elems: scala.collection.IterableOnce[A]): Unit = ???
  def prepend(elem: A) = this
  def remove(idx: Int, count: Int): Unit = ???
  def remove(idx: Int): A = ???

  // Members declared in scala.collection.mutable.Builder
  def clear(): Unit = ???
  def result(): WrappedArray[A] = ???

  // Members declared in scala.collection.mutable.Growable
  def addOne(elem: A) = this

  // Members declared in scala.collection.mutable.SeqOps
  def update(idx: Int, elem: A): Unit = ???

  // Members declared in scala.collection.SeqOps
  def apply(i: Int): A = ???
  def length: Int = ???
}
```

**Comment by sjrd** [comment]
@adriaanm Thanks, that worked. I was probably too tired yesterday evening.

**Comment by adriaanm** [comment]
A quick nap does wonders I hear 😁

**Pull request merged**
