### PR TITLE
Fix #1813: Support calling the super ctor of a JS class with : _*.

### LINKED ISSUE #1813: Support calling the super constructor of a JS class with :_*
Currently an implementation restriction wrt. #1795, coming from the implementation in #1809.

### PR DESCRIPTION
**Pull request by sjrd**
The only test for this is currently disabled (commented out), because the ECMAScript 6 output emitted for this code cannot be parsed by io.js at the moment.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0 
I tested locally the ES 5 version before commenting out the test in the second commit.

**Comment by sjrd** [comment]
And with the third commit, I tested locally the ES 6 output on Chrome Canary.

**Comment by gzm0** [comment]
Could you reference #1876 in the first commit, please?

**Comment by gzm0** [comment]
That's all. Also, this seems to need a rebase after the objects PR

**Comment by sjrd** [comment]
> Could you reference #1876 in the first commit, please?

OK. The issue did not exist yet when I made the commit.

**Comment by sjrd** [comment]
Updated.

**Comment by gzm0** [comment]
LGTM

**Comment by sjrd** [comment]
Thanks :)

**Pull request merged**
