### PR TITLE
Fix #2536: Use partest 1.0.13 for Scala 2.11.{0-2}.

### LINKED ISSUE #2536: Neg partest failing on 2.11.{0-2} in master.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by sjrd** [comment]
LGTM, although that's sad, and I fear for the long term sustainability of such a solution.

**Comment by nicolasstucki** [comment]
We should put some pressure on the releases of partest to support all previous version of Scala.

**Comment by nicolasstucki** [comment]
@sjrd you should probably rerun the weekly tests on this branch.

**Comment by sjrd** [comment]
Weekly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/4307/

**Comment by sjrd** [comment]
Weekly passed.

**Pull request merged**
