### PR TITLE
Make AbstractCollection#toString & sub-classes match Java 8 specification.

### PR DESCRIPTION
**Pull request by LeeTibbert**
Make AbstractCollection#toString match Java 8 specification.

   * The Java 8 specification for (AbstractCollection)[https://docs.oracle.com/
javase/8/docs/api/java/util/AbstractCollection.html#toString--] describes
    the resultant string as using comma-space as the separator for collections
    with size greater than one.

     Prior to this PR, ArrayDeque.scala, ArrayList, and other
     sub-classes of AbstractCollection would create a string such as
     "[a,b]". This PR corrects that to the specified "[a, b]".

   * Testing: I added three test cases to CollectionTest.scala.
      I test the zero, one, and three element cases. I also added
      a test for a custom class which overrides toString.

      I was not clever enough to figure out a way to test the case of
      instances of sub-classes of AbstractCollections containing nulls.
      Certainly ArrayDeque & ArrayList test for and reject the
      addition of null elements.

      Any Collection containing nulls would have to be tested at a level
      lower that CollectionTest. I know of no such collection, but that
      just reveals the limits of my knowledge & research.  From
      an understanding of the internals of AbstractCollection#toString,
      I expect it to handle collections containing nulls just fine.

   * Documentation: Even though this PR is a one character change 
      in two places, it warrants a brief release note.  Somebody is bound to be
      parsing the current output, probably as a CSV (comma separated
      value) list.

      I checked the Scala-js web site landing page and the documentation
      page and did not see anything affected by this PR. I did not
      check the videos, which might show present output.   I will
      remain vigilant for required changes.

### CODE REVIEW

**Comment by LeeTibbert** [comment]
From the CI failures, it became evident that I submitted this PR against the wrong branch.

I am closing this PR and hope to create a new one against the 0.6.x branch when I 
have more time & tranquility.

**Comment by sideeffffect** [comment]
@LeeTibbert the `0.6.x` branch has been merged to `master` recently. Is it a good time to reopen this PR?

**Comment by sjrd** [comment]
There's no need to reopen this PR. The work was done in 0.6.x and merged forward to master. What more do you want?

**Comment by sideeffffect** [comment]
> What more do you want?

that's exactly what I wanted! thank you guys :pray:

**Pull request closed without merging**
