### PR TITLE
Add .jvmopts

### PR DESCRIPTION
**Pull request by er1c**
I forget if this was already commented on, but it helps just running "sbt" without having to add -mem4096

### CODE REVIEW

**Comment by sjrd** [comment]
This has been proposed before, but I still don't like it. I configure my system-wide sbt to have even more memory than that (6GB), which is not necessarily appropriate for every system. I believe each user can configure their sbt to use what's reasonable in their system. Adding a `.jvmopts` prevents that.

**Comment by er1c** [comment]
@sjrd you probably work on "less projects" than the average developer, if I have multiple sbt instances open, I don't want them opening more memory than they need.

**Comment by hepin1989** [comment]
@er1c Better mention this in the contribution guide?

**Comment by er1c** [comment]
I'll close this, I'll open a PR with a `.gitignore` addition for `.jvmopts` does that work?

**Pull request closed without merging**
