### PR TITLE
Implement Integer.reverse() and Long.reverse()

### PR DESCRIPTION
**Pull request by tmgreen**
To implement `Integer.reverse()` I looked at Apache Harmony code, but NOT any Oracle or OpenJDK code.

### CODE REVIEW

**Comment by sjrd** [comment]
Thanks for your contribution. We're currently in "release process mode", where we freeze the branches and don't overload our CI servers with running tests for PRs. I'll ping you back when we're done releasing 0.6.16 (a couple days).

Also, since you're only touching the javalib, this PR should target the 0.6.x branch instead of master. Otherwise changes won't be available in 0.6.x versions.

**Comment by tmgreen** [comment]
OK sorry about that, I will try and figure out the right way to re-target this to the 0.6.x branch and get that done ASAP.

**Comment by tmgreen** [comment]
OK I've changed it to target the 0.6.x branch.

**Comment by sjrd** [comment]
Thanks. Could you rebase once more on top of the latest 0.6.x branch, so that your commit sits on top of [the Towards 0.6.17 commit](https://github.com/scala-js/scala-js/commit/85e3264f404e8b74a38e2a981c203cbec235d9d0)?

Also, it would be good to have a few more test. I suggest generating (once) 20 or so random `Int`s and 20 random `Long`s to use as test cases. I usually do that in a quick REPL session on the JVM, to get the random inputs + get the expected outputs.

**Comment by tmgreen** [comment]
OK I rebased.  Now I'll add more tests.  I had done them this way, following the model of the tests for `reverseBytes()`.  I'll add a bunch more tests for `reverseBytes()` too, I guess.

**Comment by tmgreen** [comment]
Added more test cases, both for the methods I implemented, and for the associated `reverseBytes()` methods.

**Comment by sjrd** [comment]
Dear Jenkins, test this please

**Comment by sjrd** [comment]
Thanks, it looks good. Last detail: could you squash the two commits, please? Then it's good to go.

**Comment by tmgreen** [comment]
OK it's squashed; sorry, my git-fu is a work in progress!

**Comment by sjrd** [comment]
Jenkins, retest this please

**Pull request merged**
