### PR TITLE
Fix #1929: Optimize Analizer.doReach to reduce heap allocations.

### LINKED ISSUE #1929: In fastOptJS, most tupples are being generated by a single anonymous function.
screen shot 2015-10-05 at 15 13 57

### PR DESCRIPTION
**Pull request by nicolasstucki**
Optimization based on JIT inlining and stack allocation.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by sjrd** [comment]
I take it you've checked somehow that the tuples are indeed stack-allocated?

**Comment by nicolasstucki** [comment]
I saw that with the change there are around 400'000 less objects heap allocated out of around 12'000'000 while doing a `testSuite/test:fastOptJS`. Most of them tuples.

**Comment by sjrd** [comment]
LGTM, then :)

**Pull request merged**
