### PR TITLE
Fix #2335: Fix the fast path condition of BigDecimal.longValueExact.

### LINKED ISSUE #2335: run/equality.scala is broken on master since April 12
PRs that were merged on April 11: #2317 (unlikely), #2321 (unlikely) and #2314 (by elimination, most likely culprit).

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
LGTM

**Comment by sjrd** [comment]
Updated. The previous fix was also incorrect and broke other tests.

**Comment by nicolasstucki** [comment]
It seams that we have issues with zero, we should check if the scale and presition are really what we where expecting with some tests.

**Comment by sjrd** [comment]
They are, but in fact there is no guarantee that the `scale`'th digit after the period is non-zero. So the simple check for non-whole number that we did was not valid. I simply removed that one, as `toBigIntegerExact` itself already has a fast-path for non-whole numbers.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.

**Comment by nicolasstucki** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
