### PR TITLE
Fix #3065: Cross-compile the sbt plugin for sbt 1.0.0-RC2.

### LINKED ISSUE #3065: Build and publish the sbt plugin for sbt 1.0.0-RC2
http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0-RC2

It turns out the support for cross-building an sbt plugin for 1.0.0-RC2 from a build written in 0.13.16-M1+ is quite good. So we'll be able to publish the sbt plugin of 0.6.x for sbt 1.x, in parallel to sbt 0.13.x.

### PR DESCRIPTION
**Pull request by sjrd**
Revival of #3068 after the rolled back merge.

After discussion, this is waiting for sbt 0.13.16 final to be released, so that we don't have our stable artifacts depend on sbt's pre-release artifacts.

/cc @dwijnand @eed3si9n

### CODE REVIEW

**Comment by dwijnand** [comment]
sbt 0.13.16 has been released btw.

**Comment by sjrd** [comment]
Thanks.

I amended the first commit for 0.13.16. Also I removed the shim for `@sbtUnchecked` in `SBTCompat`, since it's now part of sbt 0.13.16 itself (concerns about forward bin-compat don't apply here, because the annotation is only used on expressions within methods, and those don't survive in the bytecode).

@gzm0 Should be good to go, assuming CI passes. Once this is merged I'll release 0.6.19.

**Comment by dwijnand** [comment]
Btw I reviewed your PR and it LGTM too. (I was concerned about someone else breaking from forward compatibility, like I did with MiMa).

**Comment by gzm0** [comment]
LGTM.

**Pull request merged**
