### PR TITLE
Fix #1589: Compiler crash on switch-match with 2 guards for the same value.

### LINKED ISSUE #1589: Switch statement with "if" causes compiler to fail
```scala
import scala.util.Random

class BreakCompiler {
  val b = Random.nextInt().toByte
  val x = b >> 4 match {
    case 0xE if b == 0xE0 =>
      4
    case 0xE if b == 0xE1 =>
      5
  }
}
```

produces

```
scala.reflect.internal.FatalError:
  Found unknown label apply at RangePosition(D:\work\sandbox\bootest\src\main\scala\boo\BreakCompiler.scala, 107, 107, 109): default4()
     while compiling: D:\work\sandbox\bootest\src\main\scala\boo\BreakCompiler.scala
        during phase: jscode
     library version: version 2.11.6
    compiler version: version 2.11.6

        at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
        at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genLabelApply(GenJSCode.scala:1560)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1365)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1002)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:977)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:977)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.genBody$1(GenJSCode.scala:1908)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.apply(GenJSCode.scala:1916)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMatch$2.apply(GenJSCode.scala:1893)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMatch(GenJSCode.scala:1893)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1110)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:1984)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1075)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:930)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1102)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:911)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$42.apply(GenJSCode.scala:1983)
        at scala.collection.immutable.List.map(List.scala:277)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBlock(GenJSCode.scala:1983)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1075)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStat(GenJSCode.scala:911)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7$$anonfun$apply$9.apply(GenJSCode.scala:636)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7$$anonfun$apply$9.apply(GenJSCode.scala:610)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7.apply(GenJSCode.scala:610)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$7.apply(GenJSCode.scala:571)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodWithInfoBuilder(GenJSCode.scala:571)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:532)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$genMethod$1.apply(GenJSCode.scala:532)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.JSEncoding$class.withNewLocalNameScope(JSEncoding.scala:54)
        at org.scalajs.core.compiler.GenJSCode.withNewLocalNameScope(GenJSCode.scala:31)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethod(GenJSCode.scala:531)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:337)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:322)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1$1.apply(GenJSCode.scala:322)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$gen$1(GenJSCode.scala:322)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genClass(GenJSCode.scala:349)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:252)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1$$anonfun$apply$2.apply(GenJSCode.scala:242)
        at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:242)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$anonfun$apply$1.apply(GenJSCode.scala:224)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.apply(GenJSCode.scala:224)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:441)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:432)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:399)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
        at org.scalajs.core.compiler.GenJSCode$JSCodePhase.run(GenJSCode.scala:163)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1580)
```

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0

**Comment by gzm0** [comment]
LGTM. Did you move this around on Waffle.io?

**Comment by sjrd** [comment]
What's Waffle.io? :confused:

**Comment by gzm0** [comment]
Hahaha, a board for your GitHub issues. It seems pretty nice, but is way too intrusive IMO.

**Pull request merged**
