### PR TITLE
Fix #2523: A clean implementation of expandLongValue.

### LINKED ISSUE #2523: `run/bitsets.scala` is broken on master
Discovered by nightly:
```
!!  41 - run/bitsets.scala                         [output differs]
% diff /localhome/jenkins/a/workspace/scalajs-task-worker_2/partest/fetchedSources/2.11.8/test/files/run/bitsets-run.log /localhome/jenkins/a/workspace/scalajs-task-worker_2/partest/fetchedSources/2.11.8/test/files/run/bitsets.check
@@ -1,18 +1,4 @@
 warning: there were three deprecation warnings; re-run with -deprecation for details
-Referring to non-existent method java.lang.Long.$$bar(scala.scalajs.runtime.RuntimeLong)scala.scalajs.runtime.RuntimeLong
-  called from scala.collection.mutable.BitSet.$$bar$eq(scala.collection.mutable.BitSet)scala.collection.mutable.BitSet
-  called from TestMutable3$.<init>()
-  called from Test$.delayedEndpoint$Test$1()scala.Unit
-  called from Test$delayedInit$body.apply()java.lang.Object
-  called from scala.App$class.main(scala.App,[java.lang.String)scala.Unit
-  called from Test$.main([java.lang.String)scala.Unit
-  called from PartestLauncher$.launch
-  exported to JavaScript with @JSExport
-involving instantiated classes:
-  scala.collection.mutable.BitSet
-  Test$
-  Test$delayedInit$body
-  PartestLauncher$
 ms0 = BitSet(2)
 ms1 = BitSet(2)
 ms2 = BitSet(2)
```

### PR DESCRIPTION
**Pull request by sjrd**
As the previous comment in `expandLongValue` said, it was a trick. I thought that trick was at least *safe*, but it turns out it wasn't in some corner cases, which were exposed by `run/bitsets.scala`.

This commit fixes the issue with a clean implementation of `expandLongValue` instead of a trick.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0 if you can find a couple minutes for this today. Otherwise review by @nicolasstucki, as this issue/PR is a blocker for #2468.

I tested locally that this fixes `run/bitsets.scala`. The new test case is a direct import of the failing part of that partest.

**Comment by gzm0** [comment]
LGTM

**Comment by sjrd** [comment]
Duh! 2.10 did not have the mutable operations of `BitSet` yet. I have added an compatibility implicit class.

**Comment by gzm0** [comment]
LGTM

**Pull request merged**
