### PR TITLE
fix CrossProject scaladoc

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by gzm0** [comment]
Jenkins, ok to test

**Comment by sjrd** [comment]
Note: we entered a release cycle an hour ago, so this will have to wait until the "Towards 0.6.9" commit lands on master.

**Comment by sjrd** [comment]
@xuwei-k Could you rebase this on top of the latest master, please?

**Comment by xuwei-k** [comment]
rebased

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
