### PR TITLE
Upgrade SBT to 0.13.9, sbt-assembly to 0.14.1

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by sjrd** [comment]
I think you forgot to actually upgrade `sbt-assembly`

**Comment by soc** [comment]
@sjrd Argh... sorry, yes, you are correct. I had one in my global SBT conf, which caused me to upgrade this in the first place. Will fix.

**Comment by soc** [comment]
Updated.

**Comment by sjrd** [comment]
LGTM. Jenkins, test this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
For some strange reason, this PR causes `library/scalastyle` to fail.

**Comment by soc** [comment]
Argh ... ScalaStyle is an SBT plugin too? Maybe it needs to be updated, too...

**Comment by SethTisue** [comment]
perhaps you are running afoul of https://github.com/scalastyle/scalastyle/issues/156

**Comment by sjrd** [comment]
@SethTisue Thanks for the hint!

**Comment by sjrd** [comment]
Scalastyle 0.8.0 is out. Maybe it resolves this problem.

**Comment by soc** [comment]
@sjrd Updated.

**Comment by sjrd** [comment]
Jenkins, retest this please

**Comment by gzm0** [comment]
LGTM

**Pull request merged**
