### PR TITLE
Introduced support SecureRandom for Scala.js

### PR DESCRIPTION
**Pull request by catap**
This commit implemented a simple wrapper around `Crypto.getRandomValues()` and `java.util.Random` that covers all API for jdk13.

### CODE REVIEW

**Comment by catap** [comment]
Signed CLA

**Comment by sjrd** [comment]
Hello @catap. Thank you for your interest in contributing to Scala.js!

Unfortunately, your approach in implementing `SecureRandom`, while it might be done in a separate repo/library, cannot be used in the core Scala.js repository.

The reason is that it requires some browser-specific APIs. The core Scala.js repo is committed to implement everything in a way that is portable across all JavaScript engines supporting ES 5.1 strict or ES 2015. This is much broader than browsers, so we can never use browser-specific APIs.

**Comment by catap** [comment]
@sjrd I see your point and I've agree with it.

I can try to use approach similar to GPG4Browsers / OpenPGP.js https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/random.js but I feel that it isn't good :(

**Comment by sjrd** [comment]
Unfortunately, even that alternative approach cannot be used here, because it would only work in browsers and Node.js. There are other JS environments out there ;)

Basically, anything that relies on an API that is not specified in ECMAScript itself will be off-limit.

That does not mean that it is a complete dead end. It would be acceptable to publish a separate, non-`org.scala-js`-branded library, that would implement those APIs on a limited set of platforms.

**Comment by catap** [comment]
@sjrd their approach has downstream to just a random buffer, but I agree that it isn't secure.

**Pull request closed without merging**
