### PR TITLE
Implementation of java.util.Base64

### PR DESCRIPTION
**Pull request by mvh77**
Found 2 bugs in the jvm implementation while doing this, one has ticket JDK-8176043, the other one doesn't have one yet.

### CODE REVIEW

**Comment by gzm0** [comment]
Jenkins, ok to test

**Comment by mvh77** [comment]
Can someone tell me if I have to fix something in my code to make this work? Fails on some weirdo nodejs stuff that seems totally unrelated?

**Comment by sjrd** [comment]
I am currently abroad. I won't have time to look at it before next Monday.

**Comment by gzm0** [comment]
The test that is failing is a bootstrapping test. It tests whether the Scala.js linker compiled to JavaScript can link our test suite. It might choke on the memory size or it might be an actual optimizer bug.

You can run `sbt toolsJS/test` to run this particular test locally. If you have a full Node.js setup, the stacktraces will tell you more. I unfortunately won't have time to look at it until the end of the week and the weekend.

**Comment by sjrd** [comment]
@mvh77 Could you please [sign the CLA](https://www.lightbend.com/contribute/cla/scala)? I cannot have a look at your code before that.

**Comment by mvh77** [comment]
Done!

**Comment by mvh77** [comment]
Can you guys take a look at this?

**Comment by sjrd** [comment]
Sorry for the delay. The bootstrap failure is due to #2808, and it happens because you have that gigantic string in the tests.

I suggest you revise how you define that test to avoid for such a huge string, that you need to parse in the tests anyway. Why not define these test data in a more structured way? For example as an `Array[(String, String)]` which already are the input/encodedResult pairs?

**Comment by sjrd** [comment]
Also, I noticed that your PR is opened from your `master` branch, which is [against our contributing guidelines](https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md#pull-request-requirements). Please open a new branch with your contributions, and open a new PR from that branch.

**Pull request closed without merging**
