### PR TITLE
Backport changes to Range.scala from Scala 2.12.0-M5.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki 

/cc @lrytz Note that this PR is bit "in the blind" from my side wrt. 2.12.0-M5. Our CI will check that it stays fine wrt. M4, but it might be good to have a community build to check the fix wrt. M5.

**Comment by lrytz** [comment]
@sjrd community build with this patch is running here: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/397/console

For comparison, [the previous run](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/396/consoleFull) (without your patch) had the following errors:

```
[scala-js] [error] Referring to non-existent class scala.collection.immutable.Range$Partial$
[scala-js] [error]   called from org.scalajs.testsuite.scalalib.RangesTest.Iterable$undrange$undbug$undon$undfloating$undpoints$undissue$und1974()scala.Unit

...

[scala-js] [error] Referring to non-existent method scala.collection.immutable.Range$Partial$.by$extension(scala.Function1,java.lang.Object)java.lang.Object
[scala-js] [error]   called from org.scalajs.testsuite.scalalib.RangesTest.Iterable$undrange$undbug$undon$undfloating$undpoints$undissue$und1974()scala.Unit
[scala-js] [error]   called from org.scalajs.testsuite.scalalib.RangesTest$scalajs$junit$bootstrapper$.invoke(java.lang.Object,java.lang.String)scala.Unit
```

**Comment by nicolasstucki** [comment]
LGTM.
@lrytz is it OK community build wise?

**Comment by lrytz** [comment]
yes

**Pull request merged**
