### PR TITLE
Fixes compiled file permissions

### PR DESCRIPTION
**Pull request by janilcgarcia**
Fixes issue #4212 .

### CODE REVIEW

**Comment by janilcgarcia** [comment]
I did sign the CLA, but I don't know how can I ask GitHub to test again. Do I need to remove this PR and create another one?

**Comment by sjrd** [comment]
I reran the CLA job.

**Comment by sjrd** [comment]
Instead of using `Files.setPosixFilePermissions` after the fact, can't we create the files with the right permissions in the first place? It seems that `createTempFile` could accept that through the `FileAttribute`s, through the [`asFileAttribute`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/PosixFilePermissions.html#asFileAttribute-java.util.Set-) adapter.

**Comment by janilcgarcia** [comment]
Yes, it can be passed in `createTempFile`, but the docs on [`createTempFile`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempFile) state that it'll throw an exception if the attributes can't be set atomically when the file is created.
I thought calling `setPosixFilePermissions` separately would potentially cover systems that use POSIX permissions but can't set them atomically when creating a temp file.

If this is unnecessary, I'll just do the other way.

----

As for the guidelines, I'm sorry. I'll correct my pull request/code style according to them and create a new PR from the correct branch.

**Pull request closed without merging**
