### PR TITLE
Fix #4085: Throttle concurrent file reads

### LINKED ISSUE #4085: Failed to deserialize sjsir files on large project on scalajs 1.1.0
I see this error on a very large project at work when upgrading from scala.js 0.6.32 to 1.1.0

```scala
[info] Fast optimizing .../target/scala-2.13/scalajs-bundler/main/gondorappclient-fastopt.js
[debug] Linker: 57836 us
[error] java.io.IOException: Failed to deserialize /path-to/target/scala-2.13/classes/com/anduin/stargazer/fundsub/module/common/
FundSubZenDeskWidget$State.sjsir
[error]         at org.scalajs.linker.interface.unstable.IRFileImpl$$anonfun$withPathExceptionContext$1.applyOrElse(IRFileImpl.scala:65)
[error]         at org.scalajs.linker.interface.unstable.IRFileImpl$$anonfun$withPathExceptionContext$1.applyOrElse(IRFileImpl.scala:58)
[error]         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error]         at scala.util.Failure.recover(Try.scala:234)
[error]         at scala.concurrent.Future.$anonfun$recover$1(Future.scala:395)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Caused by: java.nio.file.FileSystemException: path-to-dir/FundSubZenDeskWidget$State.sjsir: Too many open files
[error]         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[error]         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[error]         at java.base/sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:201)
[error]         at java.base/java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:253)
[error]         at java.base/java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:311)
[error]         at org.scalajs.linker.PathIRFile$PathIRFileImpl.$anonfun$withChannel$1(PathIRFile.scala:84)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] (gondorAppClient / Compile / fastOptJS) java.io.IOException: Failed to deserialize path-to-dir/FundSubZenDeskWidget$State.sjsir
```

chat log on gitter:

sjs1

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
First step towards a solution to #4085 

@sjrd questions on this I have:
- How should we configure `maxConcurrentReads`?
- Is this the right place to address the problem (the `Analyzer` will also need throttling for full reads IMO)?

**Comment by sjrd** [comment]
>     * How should we configure `maxConcurrentReads`?

Since it addresses a system-wide limitation, which has nothing to do with a particular project or its configuration, it seems that we should configure it with a system-wide config as well. My guess would be a combination of an env var and a Java system property.

>     * Is this the right place to address the problem (the `Analyzer` will also need throttling for full reads IMO)?

The `IRLoader.ClassDefAndInfoCache.update()` will need to throttle as well, indeed. And there it actually needs to throttle in the same pool as the other `ClassDefAndInfoCache`s created by one `IRLoader`.

Other than that, it seems that it is the right place. I'm not sure where else we could take care of it.

**Comment by gzm0** [comment]
> Other than that, it seems that it is the right place. I'm not sure where else we could take care of it.

For example, we could make it the problem of an individual IRFile implementation and have it queue all reads globally. I think this solution is better, as it is more generally applicable and less magic.

> should configure it with a system-wide config as well

My general dislike of env vars / System properties aside, this has another problem: At least in the current implementation, max concurrent files is not a system-wide property: Every IRCache / Linker will track this value on its own. I think this is OK, but configuring this through a system-wide property might be very misleading :-/ (OTOH, I really don't want to introduce options for all of this :S)

**Comment by sjrd** [comment]
> For example, we could make it the problem of an individual IRFile implementation and have it queue all reads globally. I think this solution is better, as it is more generally applicable and less magic.

Right. In that case it should probably even be specific to `PathIRFile` and `PathIRContainer`.

**Comment by gzm0** [comment]
:P I meant the solution in this PR is better :) It avoids the need for backpressure. If we move the throttling into `PathIRFile` / `PathIRContainer`, we'll need unbounded queues.

**Pull request merged**
