### PR TITLE
Always use ES6 as intermediary closure input

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
@sjrd given https://github.com/scala-js/scala-js/issues/2675#issuecomment-623382097, we should close this. Do you think there is value in the first commit on its own?

**Comment by gzm0** [comment]
Seems like your concerns were justified :P The ES5 test suite seems to fail :P

**Comment by sjrd** [comment]
> Seems like your concerns were justified :P The ES5 test suite seems to fail :P

😅 

> Do you think there is value in the first commit on its own?

Yes, the first commit looks good to have.

**Comment by gzm0** [comment]
Closing. First commit is in #4033.

**Pull request closed without merging**
