### PR TITLE
Finish the refactoring of `OutputMode` into `ESFeatures`.

### PR DESCRIPTION
**Pull request by sjrd**
Instead of having a sealed abstract class with case objects, that wasn't actually sealed, and was prone to breakages, we have a principled options bag for individual features of ECMAScript that the linker is mandated and/or allowed to use.

### CODE REVIEW

**Comment by Atry** [comment]
Hi, @sjrd , did this PR fix #2675 ?

I found a related conditional expression here:

https://github.com/scala-js/scala-js/blob/df91ee0a33a2276c7a0538fd9df6ae313d96f3c5/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/ClassEmitter.scala#L1188

**Comment by Atry** [comment]
Will this PR be back-ported to 0.6.x?

**Comment by sjrd** [comment]
This PR did not change any feature. As its name very clearly says, it's only a refactoring.

The 0.6.x "backport" has already landed in 0.6.23. It was https://github.com/scala-js/scala-js/pull/3305.

**Comment by Atry** [comment]
Ah, I see.

The IIFE is introduced when converting closures, which is untouched yet, not `envFieldDef`.

https://github.com/scala-js/scala-js/blob/df91ee0a33a2276c7a0538fd9df6ae313d96f3c5/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala#L2600

**Pull request merged**
