### PR TITLE
Correct CrossProject naming

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Tested locally. Review by @sjrd

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
LGTM. You'll laugh but ... could you sign the CLA, please? ^^ Now that you don't work at epfl anymore, you're work is not automatically attributed to epfl's copyright.

**Comment by gzm0** [comment]
Hahaha, indeed :P I thought about that but then forgot.  It's done

**Comment by sjrd** [comment]
Thanks ;-)

**Pull request merged**
