### PR TITLE
Use js.native members in NodeFS

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by sjrd** [comment]
`org.scalajs.testsuite.compiler.SourceMapTest` is failing in the bootstrap tests.

**Comment by gzm0** [comment]
It seems that using a `@js.native` member protects the module from being captured as `this`:

```diff
-        $i_fs.close(fd$1, arg1$1);
+        (0, $i_fs.close)(fd$1, arg1$1);
```

Is this working as intended? (I'd assume that for ES modules this doesn't make a difference, for CommonJS it might).

**Comment by gzm0** [comment]
In fact, the source map test fails, because the linking fails:

```
org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: undefined is not an instance of java.lang.Integer
  at $throwClassCastException(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:26:9)
  at $uI(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:369:51)
  at org.scalajs.linker.NodeOutputFile$NodeOutputChannel.write(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:52183:7)
  at org.scalajs.linker.interface.unstable.OutputFileImpl.writeLoop$1(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:56637:112)
  at {anonymous}()(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:56646:169)
  at scala.scalajs.runtime.AnonFunction1.apply(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:64214:45)
  at scala.concurrent.impl.Promise$Transformation.run(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:101552:27)
  at scala.scalajs.concurrent.QueueExecutionContext$PromisesExecutionContext.scala$scalajs$concurrent$QueueExecutionContext$PromisesExecutionContext$$$anonfun$execute$2(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:70332:18)
  at {anonymous}()(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:70324:24)
Caused by: java.lang.ClassCastException: undefined is not an instance of java.lang.Integer
  at $throwClassCastException(/localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4068@3/test-suite-linker/.2.13/target/scala-2.13/scalajs-test-suite-linker-fastopt.js:26:67)
  ... 8 more
```

I suspect this simply throws before the source map is written.

**Comment by sjrd** [comment]
Ah yes, that is working as intended, since all our `@JSImport`s are specified as if they were JavaScript `import`s, and if we use actual modules in JS:
```js
// foo.mjs
export function foo() {
  return this;
}
```
```js
// main.mjs
import { foo } from "./foo.mjs"

console.log(foo());
```
```bash
$ node main.mjs
undefined
```
we can see that `this` is not bound for such a method call.

**Comment by gzm0** [comment]
```
org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: undefined is not an instance of java.lang.Integer
  at $throwClassCastException(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/scalajs-test-suite-linker-fastopt.js:26:9)
  at $uI(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/scalajs-test-suite-linker-fastopt.js:369:51)
  at org.scalajs.linker.NodeOutputFile$NodeOutputChannel.write(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/linker/js/src/main/scala/org/scalajs/linker/NodeOutputFile.scala:44:37)
  at org.scalajs.linker.interface.unstable.OutputFileImpl.writeLoop$1(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/linker-interface/shared/src/main/scala/org/scalajs/linker/interface/unstable/OutputFileImpl.scala:29:43)
  at {anonymous}()(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/linker-interface/shared/src/main/scala/org/scalajs/linker/interface/unstable/OutputFileImpl.scala:33:28)
  at scala.scalajs.runtime.AnonFunction1.apply(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:27:38)
  at {anonymous}()(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/https:/raw.githubusercontent.com/scala/scala/v2.12.11/src/library/scala/concurrent/Future.scala:307:25)
  at scala.scalajs.runtime.AnonFunction1.apply(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:27:38)
  at {anonymous}()(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/https:/raw.githubusercontent.com/scala/scala/v2.12.11/src/library/scala/concurrent/impl/Promise.scala:41:17)
  at scala.scalajs.runtime.AnonFunction1.apply(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/file:.../scala-js/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:27:38)
Caused by: java.lang.ClassCastException: undefined is not an instance of java.lang.Integer
  at $throwClassCastException(.../scala-js/test-suite-linker/.2.12/target/scala-2.12/scalajs-test-suite-linker-fastopt.js:26:67)
  ... 9 more
```

**Comment by gzm0** [comment]
The problem seems to be this diff:

```diff
-      $i_fs.write(this.Lorg_scalajs_linker_NodeOutputFile$NodeOutputChannel__f_fd, ta, 0, $uI(ta.length), (void 0), arg1$1);
+      $uI((0, $i_fs.write)(this.Lorg_scalajs_linker_NodeOutputFile$NodeOutputChannel__f_fd, ta, 0, $uI(ta.length), (void 0), arg1$1));
```

The facade for `write` has a wrong `Int` return type. It seems when calling it on a native module, no unbox is inserted. Calling a native member inserts that unbox. The unbox fails (correctly).

**Comment by gzm0** [comment]
There was a mima problem.

**Pull request merged**
