### PR TITLE
add MalformedURLException

### PR DESCRIPTION
**Pull request by yawnt**
Might be useful for someone, I needed it in a project and I took inspiration from https://github.com/scala-js/scala-js/pull/1407

### CODE REVIEW

**Comment by gzm0** [comment]
ok to test

**Comment by gzm0** [comment]
Hi, thanks for the contribution. Could you please sign the [Scala CLA][1] if you have not already done so?

[1]: https://typesafe.com/contribute/cla/scala

**Comment by gzm0** [comment]
Code looks good. Please make the first character in the commit message upper case.

**Comment by gzm0** [comment]
That's all

**Comment by yawnt** [comment]
CLA signed, commit message amended, thank you!

**Comment by gzm0** [comment]
LGTM

**Comment by gzm0** [comment]
The next release is around when @sjrd has strong mode done I assume. Since it will bring binary backwards incompatible changes, we'll probably want to pack as many of these as possible in there.

Sorry I can't be more specific about that. @sjrd, do you have a timeline?

**Comment by sjrd** [comment]
A couple weeks. That's the most precise I can give at the moment.

**Pull request merged**
