### PR TITLE
Fix package of Iterable.

### PR DESCRIPTION
**Pull request by yawnt**
should stay in `java.lang` not `java.util`

### CODE REVIEW

**Comment by nicolasstucki** [comment]
You should also add `import java.util.Iterator`

**Comment by yawnt** [comment]
Indeed I should, apologies :)

**Comment by nicolasstucki** [comment]
@sjrd can you test this please if it does not start.

**Comment by nicolasstucki** [comment]
@yawnt  you should merge the two commits

**Comment by yawnt** [comment]
:+1:

**Comment by sjrd** [comment]
Since this fixes a user-visible bug, there should be a bug report first. I created it at #1799. The commit message should reference that with `Fix #1799: Fix package of Iterable.`, or better `Fix #1799: Move Iterable to java.lang.`

**Comment by yawnt** [comment]
Done!

**Comment by sjrd** [comment]
LGTM. Jenkins, test this please

**Comment by sjrd** [comment]
Nothing compiles anymore. You should probably add `import java.lang.Iterable` in several files of the `java.util` package (because now just `Iterable` refers to Scala's `Iterable`).

**Comment by yawnt** [comment]
I fgrep'd the code and that's the only place where Iterable is used apparently. All other files reference Iterator but that is correctly under `java.util`

**Comment by sjrd** [comment]
OK but squash the commits, please.

**Comment by yawnt** [comment]
Yes, of course, sorry

**Comment by sjrd** [comment]
LGTM. Jenkins, retest this please

**Pull request merged**
