### PR TITLE
Fix #1671: Fix {Float,Double}.toInt for large abs values.

### LINKED ISSUE #1671: Double.toInt and Float.toInt are broken
They've been broken forever, because I didn't know that they were supposed to return `Int.MinValue` (resp. `Int.MaxValue`) if the floating point value is smaller than `Int.MinValue` (resp. greater than `Int.MaxValue`).

So the desugaring for `DoubleToInt` is wrong.

### PR DESCRIPTION
**Pull request by sjrd**
The behavior of `ToInt32(x)` in ES does not match the behavior of `(int) x` on the JVM for values that are lower than Int.MinValue or larger than Int.MaxValue. On the JVM, and hence for .toInt, they are clamped at Int.MinValue or Int.MaxValue, respectively. So we have to handle these cases separately.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
Isn't there be the same problems with `Short` and `Byte` with their respective min and max.

**Comment by sjrd** [comment]
`Short` and `Byte` (and `Char`) don't have that problem, because `x.toShort` is basically defined as `x.toInt.toShort` (see [JLS section 5.1.3](http://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.3)). And that's how we implement them: `x.toShort` is compiled as `DoubleToInt(x) << 16 >> 16`, for example.

**Comment by nicolasstucki** [comment]
Oh, nice and simple.
LGTM

**Comment by sjrd** [comment]
Updated. I had to add a commit fixing some of our low-level algorithms, which were relying on the buggy behavior of `x.toInt`.

**Comment by sjrd** [comment]
Rebased.
@nicolasstucki Can you review the first commit, please (Do not rely ...). The second commit hasn't changed since your first review.

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
