### PR TITLE
Assert that method name / namespace match in MethodDef

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by sjrd** [comment]
This doesn't seem to work ^^

**Comment by gzm0** [comment]
Seems we're putting JS class constructors in the public namespace. Is that intended?

**Comment by gzm0** [comment]
https://github.com/scala-js/scala-js/blob/v1.3.0/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala#L1874-L1879

**Comment by sjrd** [comment]
That doesn't really matter, because they're redecomposed and recomposed later in `genJSClassCapturesAndConstructor`. If it helps, we can use another namespace since it's only transient within `GenJSCode`.

**Comment by gzm0** [comment]
Updated. I have also consolidated some of the control flow in `genMethodWithCurrentLocalNameScope`.

**Review by sjrd — APPROVED** [review]

**Pull request merged**
