### PR TITLE
Add RejectedExecutionException.

### PR DESCRIPTION
**Pull request by yawnt**
as per title, I've added RejectedExecutionException

### CODE REVIEW

**Comment by sjrd** [comment]
OK. The title should be expressed in the imperative forum, please: "Add RejectedExecutionException."

**Comment by yawnt** [comment]
done!

**Comment by sjrd** [comment]
Er ... I meant the title of the commit. The title of the PR, I can change myself in two clicks. But I cannot amend your commit, obviously.

**Comment by yawnt** [comment]
sorry bout that, fix'd

**Comment by sjrd** [comment]
LGTM.
The next comment is addressed to the build bot.

**Comment by sjrd** [comment]
test this please

**Pull request merged**
