### PR TITLE
Upgrade to Scala 2.11.5.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
CI only.

**Comment by sjrd** [comment]
@gzm0 How do I schedule a nightly/weekly build *on this PR*? I understood how to schedule a nighly for *master* for immediate execution, but not on a PR.

**Comment by gzm0** [comment]
You have to launch a matrix-build with the right params. Take this PRs build, follow the build chain to the matrix build, relaunch another matrix build with the same params, but set matrix=nightly instead of pr.

**Comment by sjrd** [comment]
OK thanks. If I understood correctly, here they are:
Nighlty: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/1671/
Weekly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/1672/

**Comment by gzm0** [comment]
Btw, the issue number in the backport commit is wrong I think

**Comment by sjrd** [comment]
Indeed.

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
