### PR TITLE
Exclude JUnit from json-simple's transitive dependencies

### PR DESCRIPTION
**Pull request by xuwei-k**
https://code.google.com/p/json-simple/issues/detail?id=91
http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom

### CODE REVIEW

**Comment by sjrd** [comment]
Will have to be rebased on top of the Towards 0.6.7 commit when it lands in master.

**Comment by sjrd** [comment]
This should now be rebased on master.

Could you also explain why this change is needed, and what it does, exactly? I never experienced any problem.

**Comment by xuwei-k** [comment]
I just rebased on master.

Hmm, I can't explain with a specific example, but I thinks this is a just unnecessary dependency.

**Comment by sjrd** [comment]
Jenkins, test this please

**Comment by gzm0** [comment]
I agree that it doesn't make sense at all that the compile configuration (what's that in maven's / ivy's terms?) depends on `junit`.

**Comment by sjrd** [comment]
Could you make the commit message a bit clearer. Something like:

    Exclude JUnit from json-simple's transitive dependencies

    json-simple erroneously declares a dependency on JUnit, see:
    https://code.google.com/archive/p/json-simple/issues/91
    http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom

Also, as such, does this automatically exclude that double-transitive dependency from libraries that would depend on `scalajs-tools`? Or would they all have to exclude it? How does that work?

**Comment by sjrd** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
