### PR TITLE
CI ONLY Upgrade to Scala 2.13.0-M4

### PR DESCRIPTION
**Pull request by julienrf**
Continuation of #3344.

- [x] library
- [x] javalib
- [x] scalalib
- [x] compiler
- [x] testSuite
- [x] scalaTestSuite
- [x] linker
- [x] ir
- [x] partest
- [x] upgrade to latest Scala (a few things have been fixed upstream, and that will impact Scala.js)
- [x] squash commits

### CODE REVIEW

**Comment by julienrf** [comment]
I’ve updated the PR to use the latest Scala version to date (2.13.0-pre-91a7d72). I expect that after #3353 is merged the CI should run again but one test (`JSExportTest#noConflictingExport`) should still fail until https://github.com/scala/scala/pull/6561 is merged.

**Comment by sjrd** [comment]
I merged #3353. If you still get a chance to rebase this PR on top of the latest 0.6.x before you go on vacation, it would probably make the PR close to being green again. Otherwise I'll eventually do it myself.

**Comment by sjrd** [comment]
Rebased on top of #3359 and upgraded to the latest nightly of Scala.

**Comment by sjrd** [comment]
Rebased on #3361 to validate that only changing the build, tools and CI scripts on top of #3361 is enough to get the CI passing with 2.13.0-M4.

**Comment by sjrd** [comment]
No, #3361 was only a relatively small part of this PR. It contained the minimum amount of changes that we needed to get a release out supporting M4. But there's still a lot to do, e.g., the tools API. The last commit of this PR is still relevant and will come later.

For most downstream projects, though, #3361 is enough (that was the point).

**Comment by sjrd** [comment]
Almost there. Now waiting for scala-parallel-collections to be built and published for 2.13.0-M4 ... https://github.com/scala/scala-parallel-collections/issues/41

**Comment by julienrf** [comment]
Publishing the parallel collections is one month work that nobody has started yet, to my knowledge. I suggest to find a solution to not be blocked by the parallel collections.

**Comment by julienrf** [comment]
This will be fixed for 2.13.0 but in the meantime is it possible for you to disable the parallel linker?

**Comment by sjrd** [comment]
Definitely not wholesale (on all Scala versions). Doing so would mean releasing sbt plugins that perform significantly worse than the current one.

We might be able to disable it *when compiling for 2.13*, but that would involve tricky manipulations of our source files, and we would have to revert them back when support for parallel collections catches up. That's not something I'm eager to undertake.

**Comment by sjrd** [comment]
Superseded by #3702 and #3703.

**Pull request closed without merging**
