### PR TITLE
Fix #2592: Do shrink the result of Pattern.split() to an empty array.

### LINKED ISSUE #2592: Yet another String.split() inconcistency
Scala/JVM:
```scala
scala> "a".split("a")
res12: Array[String] = Array()
```
Scala.js:
```scala
Array("")
```
In the Scala.js implem we have:
```scala
    /* With `limit == 0`, remove trailing empty strings (but do not reduce
     * the array to be zero length).
     */
```
It appears the "but do not reduce the array to be zero length" is erroneous. The array can be shrunk to be empty.

However, splitting an empty string always returns an array of exactly one empty empty string.

### PR DESCRIPTION
**Pull request by sjrd**
But not if the input string is the empty string itself.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0. Best reviewed [with ?w=1](https://github.com/scala-js/scala-js/pull/2593/files?w=1)

**Comment by gzm0** [comment]
LGTM

**Comment by gzm0** [comment]
Didn't know about `w=1`. Is it new?

**Comment by sjrd** [comment]
It has existed for as long as I've been using GitHub. I sometimes recommend to use it on PRs. I'm surprised it's the first time you see me mention it.

**Pull request merged**
