### PR TITLE
Fix #2329: Add JSStringOps.normalize().

### LINKED ISSUE #2329: ES6 functions seem to be missing from JSStringsOps
for example, check normalize()

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.

**Comment by sjrd** [comment]
@nicolasstucki I'm rebasing them.

**Comment by nicolasstucki** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
