### PR TITLE
Fix #1797: Implement j.l.Math.rint().

### LINKED ISSUE #1797: Math.rint(double a) is missing
Method `Math.rint(double a)` is missing

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki 
/cc @InTheNow

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Comment by nicolasstucki** [comment]
LGTM

**Comment by InTheNow** [comment]
Nice one guys! Added to https://github.com/non/algebra/issues/74

**Pull request merged**
