### PR TITLE
Fix #1908: Add @js.native annotations in helloworld and reversi.

### LINKED ISSUE #1908: Add missing @js.native in scala-js/examples
`helloworld/fastOptJS` and `reversi/fastOptJS` are throwing warnings like:
```
[warn] /Users/nastucki/GitHub/scala-js/examples/helloworld/HelloWorld.scala:64: Classes, traits and objects inheriting from js.Any should be annotated with @js.native, unless they have @ScalaJSDefined. The default will switch to Scala.js-defined in the next major version of Scala.js. ...
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by gzm0** [comment]
Could you enable "-Xfatal-warnings" for this project? We have it disabled because of a couple of projects, but most of them actually would work with it.

**Comment by nicolasstucki** [comment]
Do not merge yet, will need rebase on #1912.

**Comment by nicolasstucki** [comment]
Added fatal warning to example projects.

**Comment by gzm0** [comment]
Neat! LGTM

**Pull request merged**
