### PR TITLE
Fix #3670: Remove workaround for GCC bug creating duplicate fields

### LINKED ISSUE #3670: Investigate whether GCC still recreates object literals with duplicate key names
See https://github.com/scala-js/scala-js/pull/3579#discussion_r287554302

### PR DESCRIPTION
**Pull request by gzm0**
I have manually verified that there are no bad object literals in the output via the generated code of `DynamicTest.should_allow_object_literals_to_have_duplicate_keys_issue_1595`. There are only `{bar:5,foo:6}` now.

### CODE REVIEW

**Comment by sjrd** [comment]
Did you manually check that GCC is not recreating a bogus object, especially with ECMAScript 5.1? (with ES 2015 it's valid to have duplicate fields in an object literal)

**Comment by gzm0** [comment]
Isn't this test enough for that: https://github.com/scala-js/scala-js/blob/v1.0.1/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/DynamicTest.scala#L291-L317?

**Comment by gzm0** [comment]
I have verified the output of fullOpt manually.

**Comment by sjrd** [comment]
> 
> 
> Isn't this test enough for that: https://github.com/scala-js/scala-js/blob/v1.0.1/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/DynamicTest.scala#L291-L317?

It's enough if we manage to run it on a JS engine that strictly implements ES 5.1. But this is a very weird thing because it wasn't valid in ES 5.1 but became valid in ES 2015. So when we test on a non-obsolete Node.js version, we wouldn't detect a regression in that particular aspect, unfortunately.

**Pull request merged**
