### PR TITLE
[no-master] Fix #3181: Enable GCC when using ECMAScript 2015 features.

### LINKED ISSUE #3181: Enable GCC for OutputMode.ECMAScript2015
Based on my [question](https://gitter.im/scala-js/scala-js?at=5a07b68f51915d962afbd867) on Gitter and @sjrd's [reply](https://gitter.im/scala-js/scala-js?at=5a07f5d186d308b755da315d):

> The ES2015 output still deactivates Closure, at the moment. For a long time Closure did not support ES2015 so we had deactivated it. **We need to revisit that one of these days.**

So the issue is for "revisiting" this topic 😄  Also if anybody can point me to some relevant documentation to read, please do.

### PR DESCRIPTION
**Pull request by sjrd**
Backport of 45ae03b2f35f2b8214c9cef794493070dac520e5.

We update `ClosureLinkerBackend` and in particular `ClosureAstTransformer` so that they understand and can translate ECMAScript 2015 features.

Combined with the version of GCC, which understands ES 2015, this allows us to enable GCC when using ES 2015 features.

The Jenkinsfile is updated to test more configurations, which become meaningful due to this change.

### CODE REVIEW

**Comment by sjrd** [comment]
Blocked by a couple of bugs in GCC v20190415, one of them already fixed in master, and the other one with a pending PR at https://github.com/google/closure-compiler/pull/3359. Hopefully we won't wait too long for the next release.

**Comment by dvkndn** [comment]
@sjrd it's a wonderful thing your PR got merged! GCC's release cycle is about 3 weeks and we are at the perfect time to expect one! (last release was about 20 days ago)

**Comment by dvkndn** [comment]
I think this is good news :D https://github.com/google/closure-compiler/releases/tag/v20190513

**Comment by sjrd** [comment]
It's not on Maven Central yet.

**Comment by sjrd** [comment]
@gzm0 This is ready for a review, although the CI won't pass yet because GCC v20190513 has not yet been published on Maven Central. When it is, AFAICT we'll just need to rerun the CI, but the code should be good as is.

**Comment by sjrd** [comment]
GCC v20190513 reached Maven Central, and CI passed :)

**Pull request merged**
