### PR TITLE
Rely on sbt's run cancellation rather than building our own

### PR DESCRIPTION
**Pull request by gzm0**
Since the upgrade to sbt 1.5.4, Ctrl+C during a run cancels it as
expected. Therefore, we remove our custom implementation of a similar
thing (which was buggy anyways, e.g. #4336).

I believe it reasonable to expect users that need this feature to
upgrade sbt.

### CODE REVIEW

**Comment by sjrd** [comment]
Do we know exactly what version of sbt introduced the correct Ctrl+C interruption? We should indicate it in the release notes.

**Comment by gzm0** [comment]
Seems like this is the commit that introduced this:
https://github.com/sbt/sbt/pull/5259/commits/8d26bc73b45fc256f1dd449e9f04df6ef5d20525

I will experimentally verify this.

**Comment by gzm0** [comment]
Hmmm... It also seems to work with sbt 1.3.13.

**Comment by gzm0** [comment]
It does not work with sbt 1.2.0. Bisecting :)

**Comment by gzm0** [comment]
works with sbt 1.3.0.

**Comment by gzm0** [comment]
Does not work with sbt 1.2.8. So 1.3.0 is the first one where it works.

**Review by sjrd — APPROVED** [review]

**Pull request merged**
