### PR TITLE
Fix #1775: Fix LinkedList.{peek,poll}{First,Last}.

### LINKED ISSUE #1775: LinkedList peek and poll methods
Peek and poll methods in LinkedList are bugged,
peekLast refer to peekFirst...
https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/LinkedList.scala#L217

and poll methods doesn't return ```null``` in case of empty list but they thorws exception.

I'm fixing this problems in the next PR.

### PR DESCRIPTION
**Pull request by andreaTP**
here you are in a separate PR

### CODE REVIEW

**Comment by sjrd** [comment]
LGTM. Jenkins, test this please

**Comment by sjrd** [comment]
CI says:
```
[error] /localhome/jenkins/c/workspace/scalajs-task-worker/test-suite/src/test/scala/org/scalajs/testsuite/javalib/LinkedListTest.scala:150:5: Whitespace at end of line
```

**Comment by andreaTP** [comment]
'azz fixed

**Comment by sjrd** [comment]
LGTM again. Jenkins, retest this please

**Comment by andreaTP** [comment]
:-) first one!

**Comment by sjrd** [comment]
Superseded by #1776

**Pull request merged**
