### PR TITLE
Fix #1594: Ensure PhantomJSEnv throws upon syntax error

### LINKED ISSUE #1594: Investigate whether PhantomJSEnv swallows webpage parse errors
Running invalid JS syntax (e.g. `{a: 1, a: 1}`) in PhantomJS should report a descriptive error. Not sure if it does.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
Hum, isn't #1594 about writing some sort of error message? How is this testing that at all? What do we gain by this test? 

Also, anyway it should be in the tests common to all engines. As written, it's not specific to PhantomJS in the least.

**Comment by gzm0** [comment]
It's about our instrumentation code (inside PhantomJS) failing if there is a syntax error and not just completing successfully. So yes, it does apply to all VMs, but is unnecessary since it would just be testing very basic VM functionality. In the case of PhantomJS, we test [this code][1].

[1]: https://github.com/scala-js/scala-js/blob/master/js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala#L403-L460

**Comment by sjrd** [comment]
Hum OK. I still don't know what fixed the mentioned issue, though. Apparently there was an issue, and now it's magically gone?

**Comment by gzm0** [comment]
There was no issue. Based on some discussion on gitter, I was just not sure whether our PhantomJS instrumentation code handles this case. Apparently it does. So adding a test is sufficient.

Would you like me to alter the commit message?

**Comment by sjrd** [comment]
LGTM
Ah, OK.

**Pull request merged**
