### PR TITLE
Retry failed jobs once

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
This PR does not really change how we dispatch jenkins jobs, since this configuration lies on the Jenkins server. Review by @sjrd. If you are OK with the change, I will do the following:

1. Deploy the change to Jenkins
2. Test the change
3. Merge the change

**Comment by gzm0** [comment]
[Build Flow Doc](https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin)

**Comment by sjrd** [comment]
LGTM

**Comment by gzm0** [comment]
retest this please

**Comment by gzm0** [comment]
The jobs do spawn. New script is OK. Merging this.

**Pull request merged**
