### PR TITLE
Fix #2249: Fix the output of scalajsp -i.

### LINKED ISSUE #2249: Info printer output is garbled
```
encodedName: Lhelloworld_HelloWorld$
isExported: true
kind: ModuleClass
superClass: Some(O)
interfaces: [sjs_js_JSApp]
methods:
  $$js$exported$meth$main__O:
    staticMethodsCalled:
      
    
  main__V:
    methodsCalled:
      sjs_js_Any$: [: [fromInt__I__sjs_js_Any}
      Lhelloworld_HelloWorld$: [: [useMyTrait__Lhelloworld_MyTrait__V, useParamTrait__Lhelloworld_ParamTrait__V, foo$1__p1__F1__sjs_js_Any, doWithBody$1__p1__F0__V}
    methodsCalledStatically:
      sjsr_AnonFunction0: [init___sjs_js_Function0}
      Lhelloworld_HelloWorld$$anonfun$main$2: [init___}
      sjsr_AnonFunction1: [init___sjs_js_Function1}
    instantiatedClasses: [Lhelloworld_MyJSClass, sjsr_AnonFunction1, Lhelloworld_HelloWorld$$anonfun$main$2, sjs_js_Object, sjsr_AnonFunction0]accessedModules: [sjs_js_Any$]
  useParamTrait__Lhelloworld_ParamTrait__V:
    methodsCalled:
      s_Predef$: [: [println__O__V}
    accessedModules: [s_Predef$]
  useMyTrait__Lhelloworld_MyTrait__V:
    methodsCalled:
      s_Predef$: [: [println__O__V}
    accessedModules: [s_Predef$]
  doWithBody$1__p1__F0__V:
    
  foo$1__p1__F1__sjs_js_Any:
    methodsCalled:
      F1: [: [apply__O__O}
    
  init___:
    methodsCalledStatically:
      O: [init___}
    staticMethodsCalled:
      O: [init___}
    
  main:
    isExported: true
    methodsCalled:
      Lhelloworld_HelloWorld$: [: [$$js$exported$meth$main__O}
```

### PR DESCRIPTION
**Pull request by sjrd**
New output:
```
encodedName: Lhelloworld_HelloWorld$
isExported: true
kind: ModuleClass
superClass: Some(O)
interfaces: [sjs_js_JSApp]
methods:
  $$js$exported$meth$main__O:
    staticMethodsCalled:
      sjs_js_JSApp$class: [$$js$exported$meth$main__sjs_js_JSApp__O]
    
  main__V:
    methodsCalled:
      Lhelloworld_HelloWorld$: [sayHelloFromDOM__V, sayHelloFromTypedDOM__V, sayHelloFromTypedJQuery__V, sayHelloFromJQuery__V]
      sjs_js_Dynamic$: [global__sjs_js_Dynamic]
      s_Predef$: [println__O__V]
      sjs_js_DynamicImplicits$: [truthValue__sjs_js_Dynamic__Z]
      sjs_js_Any$: [fromString__T__sjs_js_Any]
    accessedModules: [s_Predef$, sjs_js_Dynamic$, sjs_js_Any$, sjs_js_DynamicImplicits$]
  sayHelloFromDOM__V:
    methodsCalled:
      sjs_js_Any$: [fromString__T__sjs_js_Any]
      sjs_js_Dynamic$: [global__sjs_js_Dynamic]
    accessedModules: [sjs_js_Dynamic$, sjs_js_Any$]
  sayHelloFromTypedDOM__V:
    
  sayHelloFromJQuery__V:
    methodsCalled:
      sjs_js_Any$: [fromString__T__sjs_js_Any]
      sjs_js_Dynamic$: [global__sjs_js_Dynamic]
    accessedModules: [sjs_js_Dynamic$, sjs_js_Any$]
  sayHelloFromTypedJQuery__V:
    
  init___:
    methodsCalledStatically:
      O: [init___]
    staticMethodsCalled:
      sjs_js_JSApp$class: [$$init$__sjs_js_JSApp__V]
    
  main:
    isExported: true
    methodsCalled:
      Lhelloworld_HelloWorld$: [$$js$exported$meth$main__O]
```

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by gzm0** [comment]
Thanks for the fix. Can we have a test for the printers? The repeatedly break and we don't notice...

**Comment by sjrd** [comment]
OK I'll try to come up with some test infrastructure for that. Probably some simple unit tests, in fact.

**Comment by gzm0** [comment]
Yeah, nothing fancy. Just a test that constructs a dummy info, feeds it to the printer and asserts the result.

**Comment by nicolasstucki** [comment]
LGTM.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.

**Pull request merged**
