### PR TITLE
Fix #1752: Build for and upgrade to Scala 2.11.7.

### LINKED ISSUE #1752: Build for Scala 2.11.7

### PR DESCRIPTION
**Pull request by sjrd**
Nothing special to report. A few more whitelisted and blacklisted partests. There was no change in the overridden files in the scalalib wrt. 2.11.6.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki and @gzm0 
I'll launch nightly on this PR after the review, and when the pressure on Jenkins will be lessened.

**Comment by nicolasstucki** [comment]
LGTM

**Comment by sjrd** [comment]
Rebased.

**Comment by gzm0** [comment]
LGTM

**Comment by sjrd** [comment]
Updated checksizes after rebase.

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please

**Pull request merged**
