### PR TITLE
Add the ECMAScript 6 target to the CI, using io.js >= 2.0.0.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by gzm0** [comment]
Ouch... LGTM though.

**Comment by gzm0** [comment]
That was probably my fault :-/

**Comment by sjrd** [comment]
```
[error] PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/52239e80-d495-9c13-38dbd7c9-2d8c4010.dmp
org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
```
I think we're in big trouble. It seems our test suite is now simply too much to bear for PhantomJS. At least v1.x.

I'll defer this fix to the CI script to different PR, and only keep the io.js stuff here.

**Comment by gzm0** [comment]
:( That's why we never encountered the crashes others have seen...

**Comment by sjrd** [comment]
Yep, indeed. :-(

**Comment by gzm0** [comment]
https://github.com/sjrd/scala-js/commit/e617f0806a13cef84672f44b1e7474815b0e6728#diff-541c4114932b6b401c8ab89d6c392957R68 :(

**Comment by sjrd** [comment]
The good news is, *locally* I can still run the test suite with PhantomJS, both in FastOpt and FullOpt. So it's not completely broken. It still has to do with the machine being slow/having few RAM.

**Comment by sjrd** [comment]
Before I forget: it *might* be that it deterministically crashes on `IntTest`.

**Comment by sjrd** [comment]
Yea, that works :-)
Review by @gzm0 
/cc @nicolasstucki

**Comment by gzm0** [comment]
LGTM

**Pull request merged**
