### PR TITLE
(Possibly) a faster StringBuilder

### PR DESCRIPTION
**Pull request by s5bug**
Attempts to modify StringBuilder to be backed by `Uint16Array`.

Current issues:
- [ ] Compilation fails somewhere in the IR processing phase; the needed reference to `String.fromCharCode.apply(null, ` is most likely the culprit, but I don't know how to fix it
- [ ] Out-of-bounds accesses are not checked for properly on many members

Future issues:
- [ ] This should be benchmarked against the original implementation, it's not guaranteed to be faster

### CODE REVIEW

**Comment by sjrd** [comment]
Could you confirm that you did not look at the source code of any other JDK implementation? *Especially* GPL-licensed ones, like OpenJDK.

**Comment by s5bug** [comment]
I have looked at the source code of OpenJDK once in the past for _only_ `Objects.equals` and _nothing else_.

**Comment by sjrd** [comment]
OK that's fine, since this PR does not touch `java.util.Objects` nor anything that resembles it.

**Comment by sjrd** [comment]
> Compilation fails somewhere in the IR processing phase; the needed reference to `String.fromCharCode.apply(null, ` is most likely the culprit, but I don't know how to fix it

About that, I think the best thing to do is to add handling for non-empty `path`s in `JSNativeLoadSpec.Global` at
https://github.com/scala-js/scala-js/blob/a4560ed794a1fa2e095a21b0e05212b3a08c2df9/project/JavalibIRCleaner.scala#L272-L283

**Comment by s5bug** [comment]
How should I go about that?

**Comment by sjrd** [comment]
Fold over the path with `JSBracketSelect`s, so that
```scala
JSNativeLoadSpec.Global("Foo", List("bar", "baz"))
```
becomes
```scala
JSBracketSelect(JSBracketSelect(JSGlobalRef("Foo"), StringLiteral("bar")), StringLiteral("baz"))
```

**Comment by s5bug** [comment]
Should the "without \`.\`" be removed here? https://github.com/scala-js/scala-js/blob/a34cd9772429c23c651ed7b67448687d807423f8/project/JavalibIRCleaner.scala#L280

**Comment by sjrd** [comment]
> Should the "without `.`" be removed here?
> 
> https://github.com/scala-js/scala-js/blob/a34cd9772429c23c651ed7b67448687d807423f8/project/JavalibIRCleaner.scala#L280

Yes, indeed.

**Pull request closed without merging**
