### PR TITLE
Fix #4672: Load loopback modules asynchronously

### LINKED ISSUE #4672: ExportsTest.exportsNamespace setup is flaky
Seems like we're hit by this race condition:

https://github.com/scala-js/scala-js/blob/0aa270f2d0558e85b508aab6f2b5c76e312ec295/project/Build.scala#L2037-L2047

FWIW, this is not the first time I'm seeing this.

_Originally posted by @gzm0 in https://github.com/scala-js/scala-js/issues/4671#issuecomment-1120374350_

### PR DESCRIPTION
**Pull request by gzm0**
The export-loopback script comes from a time where we didn't have
async testing support.

### CODE REVIEW

**Comment by gzm0** [comment]
Seems like GCC is not happy about this:

```
java.lang.IllegalStateException: AST should not contain Dynamic module import. Reference node:

[error] DYNAMIC_IMPORT 42:48  [source_file: file:///localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4673/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala] [input_id: InputId: file:///localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4673/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]

[error]     STRINGLIT ./main.js 39:16  [source_file: file:///localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4673/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala] [input_id: InputId: file:///localhome/jenkins/sjsjenkins/workspace/scalajs-main_PR-4673/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]
```

**Comment by gzm0** [comment]
Related:

https://github.com/google/closure-compiler/issues/3707
https://github.com/google/closure-compiler/pull/3706

**Comment by sjrd** [comment]
That lack of support in GCC is probably going to make this solution a non-starter.

However, it gave me an idea. We could turn `explicitlySetExportsNamespaces` into a (Scala) `Promise/Future`, which the tests `map` on, and which `setExportsNamespaceForExportsTest` fulfills. When `setExportsNamespaceForExportsTest` is not required, it would fulfilled immediately upon creation. Does that make sense?

**Comment by gzm0** [comment]
> Does that make sense?

yes, absolutely. But the GCC error message lets me suspect that we're just not configuring it right. (IIUC it should have passthrough for `JSImport` if so, we should configure it so it works, also for SJS users).

**Comment by gzm0** [comment]
Seems closure simply refuses to process the dynamic import, because our ESLevel isn't set high enough:
https://github.com/google/closure-compiler/blob/f57390c98695ef033ef36bdd9f0bf69a6017ae59/src/com/google/javascript/jscomp/parsing/parser/FeatureSet.java#L228-L229

Dynamic imports are in ES2020 only. That actually raises a question for our own linker as well: Should we disallow dynamic imports in case the ES level is too low?

**Comment by gzm0** [comment]
Seems closure simply refuses to process the dynamic import, because our ESLevel isn't set high enough:
https://github.com/google/closure-compiler/blob/f57390c98695ef033ef36bdd9f0bf69a6017ae59/src/com/google/javascript/jscomp/parsing/parser/FeatureSet.java#L228-L229

Dynamic imports are in ES2020 only. That actually raises a question for our own linker as well: Should we disallow dynamic imports in case the ES level is too low?

**Comment by sjrd** [comment]
> Should we disallow dynamic imports in case the ES level is too low?

No, I don't think so. For the same reason that we don't disallow the `ESModule` kind in ES 5.1: these things are very often processed away by bundlers, although they don't touch anything else in the code.

**Comment by gzm0** [comment]
I have ended up using separate compilation depending on the module mode (for `ExportsTest`). As a result, we can use `js.dynamicImport` everywhere, avoiding the GCC issue.

**Review by sjrd — APPROVED** [review]
Nice! Looks great. :)

**Pull request merged**
