### PR TITLE
Delete unused files from tools

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
I don't think `CacheUtils` is used in the `0.6.x` branch. If you want I can split the commit or deprecate it there.

**Comment by sjrd** [comment]
> I don't think CacheUtils is used in the 0.6.x branch. If you want I can split the commit or deprecate it there.

No, it's not worth it.

**Comment by sjrd** [comment]
There's a Scaladoc error:
```
[info] Main Scala API documentation to /localhome/jenkins/a/workspace/scalajs-task-worker/tools/jvm/target/scala-2.11/api...
model contains 239 documentable templates
[error] /localhome/jenkins/a/workspace/scalajs-task-worker/tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala:53: Could not find any member to link for "org.scalajs.core.tools.javascript.OutputMode".
[error]   /** Verify that a [[LinkingUnit]] corresponds to this [[LinkerBackend]]'s
[error]   ^
[error] one error found
[error] (tools/compile:doc) Scaladoc generation failed
```

**Comment by gzm0** [comment]
Updated.

**Pull request merged**
