### PR TITLE
Fix #1664: Check @JSName on classes for literals

### LINKED ISSUE #1664: @JSName(variable) annotation does not fail on objects and classes
```
object Constants {
  def CONST_1 = "bar"
}


import Constants._

@JSName(CONST_1)
object foo extends js.Object {
 ...
}
```
When i'm calling `fastOptJS` and `fullOptJS`, no error occurs, but it should.
When i'm running this code in browser, `foo is undefined` runtime exception occurs.
scala.js 0.6.3.

Normally, some like this must be thrown during compile:
```
[error] TestCase.scala:8: The argument to JSName must be a literal string
[error]   @JSName(CONST_1)
[error]    ^
[error] one error found
```

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
Your commit messages misses its ending `.`
That's all.

**Comment by gzm0** [comment]
Updated

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
