### PR TITLE
Remove java.time

### PR DESCRIPTION
**Pull request by nicolasstucki**
java.time will not be included in 0.6.6 and therefore
removed. Currently java.time has been extracted into
the project scala-js/scala-js-java-time as an external
library. It could be merged back in later on when its
implementation has matured.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Do not merge until https://github.com/scala-js/scala-js-java-time/pull/1 is merged.

**Comment by sjrd** [comment]
Looks good to me. Waiting for the other one to be merged to write a real LGTM.

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js-java-time/pull/1 has been merged.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
