### PR TITLE
Fix #1979: Fix divideToIntegralValue scaling with doubles.

### LINKED ISSUE #1979: java.math.BigDecimal.divideToIntegralValue fails with some Doubles.
For example:
```scala
new BigDecimal(3.21).divideToIntegralValue(new BigDecimal(1.0))
```
will return `300000000000000000000000000000000000000000000000000`.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
I would squash the commits. Otherwise OK.

**Comment by sjrd** [comment]
Ah but the commit message should still mention that it "also fixes #1974" or something like that.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
