### PR TITLE
Fix #2238: Drop support for Strong Mode.

### LINKED ISSUE #2238: Drop support for Strong Mode
https://groups.google.com/forum/#!topic/strengthen-js/ojj3TDxbHpQ

> Considering all that, we have reluctantly decided not to pursue strong mode further. We learned some worthwhile lessons, but overall it is not clear that the benefits justify the costs. Starting with the next version of V8, we will hence remove support for strong mode.

So Strong Mode is a failure and will be removed from V8. Time for us to get rid of it too ;)

### PR DESCRIPTION
**Pull request by sjrd**
As was announced in
https://groups.google.com/forum/#!topic/strengthen-js/ojj3TDxbHpQ
the Strong Mode experiment has been canceled, and support for Strong
Mode will be progressively removed from V8.

There is therefore no point supporting Strong Mode anymore.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki and @gzm0

**Comment by gzm0** [comment]
I assume you `git grep`ed for various combinations of "strong mode" and didn't find anything anymore. If so: LGTM

**Comment by sjrd** [comment]
I searched for "strong" in the GitHub interface: https://github.com/scala-js/scala-js/search?utf8=%E2%9C%93&q=strong

**Comment by gzm0** [comment]
I checked with `git grep` as well. You seemed to have caught everything.
LGTM.

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
