### PR TITLE
Fix #1967: LocalTime.isSupported should return false for null

### LINKED ISSUE #1967: LocalTime.isSupported(null) throws
In the ScalaJS implementation `java.time.LocalTime.isSupported(x)`throws a `NullPointerException` both for `x = null: ChronoUnit` and `x = null: ChronoField`, whereas it should return `false` according to the [JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#isSupported-java.time.temporal.TemporalField-).

### PR DESCRIPTION
**Pull request by ummels**
Fixes #1967

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Change the message of the commit to `Fix #1967: ...`

**Comment by nicolasstucki** [comment]
I assume this will need to be rebased after #1964 is merged.

**Comment by ummels** [comment]
Yes, this has to wait for #1964 to be merged.

**Comment by nicolasstucki** [comment]
@ummels now you can rebase.

**Comment by nicolasstucki** [comment]
@ummels now you can rebase.

**Comment by ummels** [comment]
Rebased. Please test.

**Comment by sjrd** [comment]
Jenkins, test this please

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
