### PR TITLE
Fix #2023: Fix CopyOnWriteArrayList type parameter bound.

### LINKED ISSUE #2023: CopyOnWriteArrayList constructor can't be used
When I try to use the `Array[E]` constructor for `CopyOnWriteArrayList` I get this:

```scala
[info] Fast optimizing /home/travis/code/projects/circe/tests/js/target/scala-2.11/circe-tests-test-fastopt.js
[error] Referring to non-existent method ju_concurrent_CopyOnWriteArrayList.init___AO
[error]   called from Lio_circe_Printer$MemoizedPieces.init___
[error]   called from Lio_circe_MemoizedPiecesSuite$$anon$1.init___Lio_circe_MemoizedPiecesSuite
[error]   called from Lio_circe_MemoizedPiecesSuite.makePieces__Lio_circe_Printer$MemoizedPieces
[error]   called from Lio_circe_MemoizedPiecesSuite.init___
[error]   called from Lio_circe_MemoizedPiecesSuite.__exportedInits
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lio_circe_MemoizedPiecesSuite
java.lang.RuntimeException: There were linking errors
        at scala.sys.package$.error(package.scala:27)
```

Diagnosis by @sjrd [here](https://gitter.im/scala-js/scala-js?at=5648c311bb11d072795968d4).

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
Did you check that we don't have any *other* collection taking `Array[E]`s that would also need fixing?

**Comment by nicolasstucki** [comment]
No, I will check.

**Comment by nicolasstucki** [comment]
It was the only one.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
