### PR TITLE
Fix #3433: Report underflow for incomplete multibyte UTF-8 chars.

### LINKED ISSUE #3433: UTF-8 CharsetDecoder doesn't handle incomplete character ranges correctly
Trying to consume a bytebuffer with an incomplete character at the end of a buffer should result in rejecting the buffer and returning underflow, rather than handling it as an invalid byte sequence.

As seen on https://scalafiddle.io/sf/WsaQcxb/0

I have not minimized whether the issue is in CharsetDecoder's `decode` method, or in the `decodeLoop` method of the UTF-8 decoder.

### PR DESCRIPTION
**Pull request by sjrd**
make it return underflow instead of coding error, since there may
still be more input

### CODE REVIEW

**Comment by sjrd** [comment]
It looks like `testSuiteJVM/test` is failing.

**Comment by martijnhoekstra** [comment]
Yes. I have no idea how I managed to mess this up, but I did -- maybe commits got lost in the reset/rebase/clean attempts I made, maybe I did something else silly. 

https://github.com/martijnhoekstra/scala-js/commit/e631f424c1a1e1d0d2880a662bd5247acca769e9

**Comment by sjrd** [comment]
LGTM. I'll take care of the coding style.

**Comment by sjrd** [comment]
I've pushed to https://github.com/sjrd/scala-js/tree/utf8 a revised version with the correct coding style, and a commit message that matches [our guidelines](https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages). Could you checkout that commit and force-push it to your branch please? So that we can wrap up this PR.

    $ git checkout utf8
    $ git remote add sjrd git@github.com:sjrd/scala-js.git
    $ git fetch sjrd
    $ git reset --hard sjrd/utf8
    $ git push --force origin utf8

Thanks :D

**Comment by sjrd** [comment]
Thank you @martijnhoekstra!

**Comment by martijnhoekstra** [comment]
thank you for all your help pulling this across the finish line.

**Pull request merged**
