### PR TITLE
Fix #2071: `Duration.ofSeconds(Long.MinValue).dividedBy(-1)`

### LINKED ISSUE #2071: `Duration.ofSeconds(Long.MinValue).dividedBy(-1)` returns a Duration
It should throw an `ArithmeticException` as does `Duration.ofSeconds(Long.MinValue).negated`.

### PR DESCRIPTION
**Pull request by ummels**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Jenkins, test this please.

**Comment by nicolasstucki** [comment]
LGTM

**Comment by ummels** [comment]
Looks like a spurious failure?

**Comment by sjrd** [comment]
It's #2075. Stand by for now.

**Comment by nicolasstucki** [comment]
@ummels, you will need to rebase if we want the tests to pass. #2075 has been fixed.

**Comment by ummels** [comment]
Rebased.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
