### PR TITLE
Fix #2688: Upgrade to Scala 2.12.1.

### LINKED ISSUE #2688: Upgrade to Scala 2.12.1

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0

**Comment by gzm0** [comment]
Maybe mention in the second commit, that this fixes #2591.

**Comment by gzm0** [comment]
```
java.io.FileNotFoundException: /localhome/jenkins/a/workspace/scalajs-task-worker_2/scala-test-suite/src/test/resources/2.12.1/WhitelistedTests.txt

# Failed test paths (this command will update checkfiles)
partest --update-check \
  /localhome/jenkins/a/workspace/scalajs-task-worker/partest/fetchedSources/2.12.1/test/files/neg/t6446-additional \
  /localhome/jenkins/a/workspace/scalajs-task-worker/partest/fetchedSources/2.12.1/test/files/neg/t6446-missing \
  /localhome/jenkins/a/workspace/scalajs-task-worker/partest/fetchedSources/2.12.1/test/files/neg/t6446-show-phases.scala \
  /localhome/jenkins/a/workspace/scalajs-task-worker/partest/fetchedSources/2.12.1/test/files/neg/t7494-no-options
```

**Comment by sjrd** [comment]
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/4703/
Weekly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/4704/

**Comment by sjrd** [comment]
Nightly and weekly passed.

**Pull request merged**
