### PR TITLE
Fix #2228: Fix handling of signs in `new BigInteger(String)`.

### LINKED ISSUE #2228: BigInt("+100000000") crashes
```scala
println(BigInt("100000000"))
println(BigInt("-100000000"))
println(BigInt("+10000000"))
println(BigInt("+100000000"))
```
causes:
```
100000000
-100000000
10000000
java.lang.NumberFormatException: For input string: "+"
    at $c_jl_NumberFormatException.$c_jl_Throwable.fillInStackTrace__jl_Throwable (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\library\src\main\scala\scala\scalajs\runtime\StackTrace.scala:33:5)
    at $c_jl_NumberFormatException.$c_jl_Throwable.init___T__jl_Throwable (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\Throwables.scala:12:19)
    at $c_jl_NumberFormatException.init___T (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\Throwables.scala:325:48)
    at $c_jl_Integer$.fail$1__p1__T__sr_Nothing$ (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\Integer.scala:77:48)
    at $c_jl_Integer$.parseInt__T__I__I (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\Integer.scala:86:24)
    at $c_Ljava_math_BigInteger.setFromString__p2__T__I__V (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalib\src\main\scala\java\math\BigInteger.scala:913:5)
    at $c_Ljava_math_BigInteger.init___T__I (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalib\src\main\scala\java\math\BigInteger.scala:233:23)
    at $c_Ljava_math_BigInteger.init___T (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\javalib\src\main\scala\java\math\BigInteger.scala:236:7)
    at $c_s_math_BigInt$.apply__T__s_math_BigInt (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\https:\raw.githubusercontent.com\scala\scala\v2.11.7\src\library\scala\math\BigInt.scala:77:5)
    at $c_Lhelloworld_HelloWorld$.main__V (C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\target\scala-2.11\file:\C:\Users\Sepi\Documents\Projets\scalajs\examples\helloworld\HelloWorld.scala:12:14)
```

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
LGTM

**Comment by sjrd** [comment]
Well, the `assertThrows` fix reveals other bugs. I'll move it out of the PR.

And apparently JDK6 had the same bug as that described by #2228, so I'll have to disable that test on JDK 6 JVM.

**Comment by sjrd** [comment]
Updated.

**Comment by nicolasstucki** [comment]
LGTM

**Pull request merged**
