### PR TITLE
Fix #2480: Handle framework bugs in HTML runner

### LINKED ISSUE #2480: HTML runner can crash with buggy test framework

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
LGTM, assuming you have tested locally?

**Comment by gzm0** [comment]
>  assuming you have tested locally?

I have tested that it still runs and the scheduling does not block the UI thread.

Do you want me to reproduce a failure in a test framework?

**Comment by gzm0** [comment]
Note: #2518

**Comment by sjrd** [comment]
> Do you want me to reproduce a failure in a test framework?

That would be good, I think.

**Comment by gzm0** [comment]
Updated.

I manually tested by adding a probabilistic `sys.error` in [`JUnitTask`](https://github.com/scala-js/scala-js/blob/master/junit-runtime/src/main/scala/org/scalajs/junit/JUnitTask.scala#L16).

This reported the `sys.error` failure in the individual suite and the state exception (that not all tasks have been run) in the overall report. As a side note: The testing made me discover a bug (failure was not recovered in individual run).

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
Needs a rebase.

**Comment by gzm0** [comment]
Updated.

**Comment by sjrd** [comment]
LGTM

**Pull request merged**
