### PR TITLE
Update closure-compiler to v20221102

### PR DESCRIPTION
**Pull request by plokhotnyuk**

### CODE REVIEW

**Comment by sjrd** [comment]
Since [v20220601](https://github.com/google/closure-compiler/wiki/Releases#june-1st-2022-v20220601), GCC requires JDK 11. :( It's unlikely that we will be able to upgrade past v20220502. :(

**Comment by strelec** [comment]
Can you detect which JDK is present on the system and pick accordingly, or make it a part of config? It is only a compile-time dep after all, not a runtime requirement.

**Comment by sjrd** [comment]
Perhaps right now, but soon enough there will be a binary incompatible change (we went through quite a lot of those) and then it will break in an unrecoverable way.

**Comment by strelec** [comment]
The fact that such a large project as closure-compiler finally dropped Java 8, is a good sign we shall do the same.

**Comment by sjrd** [comment]
Tell that to maintainers of important libraries of the Scala ecosystem. Until virtually every library supporting Scala.js drops support for JDK 8, we have to keep it.

**Comment by gzm0** [comment]
Can we selectively drop GCC support on Java 8? If yes, it might be a good compromise

**Comment by sjrd** [comment]
That would be very hard to set up in terms of build and CI infrastructure. In particular, for publishing, since we have to build the published artifacts on JDK 8 to ensure compatibility. How would the linker be built on JDK 8 if it depends on a library that requires JDK 11?

**Comment by armanbilge** [comment]
> In particular, for publishing, since we have to build the published artifacts on JDK 8 to ensure compatibility.

Why not use the `--release` flag? It lets you build on a new JDK while ensuring compatibility with an old one.

**Comment by gzm0** [comment]
> Why not use the --release flag? It lets you build on a new JDK while ensuring compatibility with an old one.

That is not enough. We also need to make sure we're not depending ourselves on things of a higher JDK (e.g. libs).

If we want to do this, I don't think we'd get around setting up a hybrid JDK build. I.e. building different sbt projects on different JVM versions.

**Pull request closed without merging**
